const cvcLadderWords = [
  "bag", "bat", "bed", "beg", "bib", "bin", "bot", "box", "bug", "bun",
  "bus", "cab", "can", "cap", "cat", "cod", "cop", "cot", "cub", "cup",
  "cut", "dad", "dam", "den", "dig", "doc", "dog", "dot", "dug", "fan",
  "fin", "gap", "gum", "ham", "hat", "hen", "hid", "hip", "hit", "hog",
  "hop", "hot", "hug", "hut", "jag", "jet", "jig", "job", "jog", "jug",
  "kid", "kit", "lab", "leg", "lid", "lip", "lit", "lob", "log", "mad",
  "man", "map", "mat", "mom", "mop", "mud", "mug", "nap", "net", "nut",
  "pad", "pan", "pen", "pet", "pig", "pin", "pit", "pop", "pot", "pug",
  "pup", "rag", "ram", "rat", "rib", "rig", "rim", "rip", "rob", "rod",
  "rug", "run", "sad", "sap", "sip", "sit", "sob", "sub", "sun", "tag",
  "tap", "ten", "tin", "top", "tub", "tug", "tux", "van", "vet", "wag",
  "wax", "web", "wed", "wig", "win", "zap", "zip", "fix", "fox", "six",
  "sax", "men"

];

const cvcLadderImages = {
  "bag": "images/bag.png",
  "bat": "images/bat.png",
  "bed": "images/bed.png",
  "beg": "images/beg.png",
  "bib": "images/bib.png",
  "bin": "images/bin.png",
  "bot": "images/bot.png",
  "box": "images/box.png",
  "bug": "images/bug.png",
  "bun": "images/bun.png",
  "bus": "images/bus.png",
  "cab": "images/cab.png",
  "can": "images/can.png",
  "cap": "images/cap.png",
  "cat": "images/cat.png",
  "cod": "images/cod.png",
  "cop": "images/cop.png",
  "cot": "images/cot.png",
  "cub": "images/cub.png",
  "cup": "images/cup.png",
  "cut": "images/cut.png",
  "dad": "images/dad.png",
  "dam": "images/dam.png",
  "den": "images/den.png",
  "dig": "images/dig.png",
  "doc": "images/doc.png",
  "dog": "images/dog.png",
  "dot": "images/dot.png",
  "dug": "images/dug.png",
  "fan": "images/fan.png",
  "fin": "images/fin.png",
  "gap": "images/gap.png",
  "gum": "images/gum.png",
  "ham": "images/ham.png",
  "hat": "images/hat.png",
  "hen": "images/hen.png",
  "hid": "images/hid.png",
  "hip": "images/hip.png",
  "hit": "images/hit.png",
  "hog": "images/hog.png",
  "hop": "images/hop.png",
  "hot": "images/hot.png",
  "hug": "images/hug.png",
  "hut": "images/hut.png",
  "jag": "images/jag.png",
  "jet": "images/jet.png",
  "jig": "images/jig.png",
  "job": "images/job.png",
  "jog": "images/jog.png",
  "jug": "images/jug.png",
  "kid": "images/kid.png",
  "kit": "images/kit.png",
  "lab": "images/lab.png",
  "leg": "images/leg.png",
  "lid": "images/lid.png",
  "lip": "images/lip.png",
  "lit": "images/lit.png",
  "lob": "images/lob.png",
  "log": "images/log.png",
  "mad": "images/mad.png",
  "man": "images/man.png",
  "map": "images/map.png",
  "mat": "images/mat.png",
  "mom": "images/mom.png",
  "mop": "images/mop.png",
  "mud": "images/mud.png",
  "mug": "images/mug.png",
  "nap": "images/nap.png",
  "net": "images/net.png",
  "nut": "images/nut.png",
  "pad": "images/pad.png",
  "pan": "images/pan.png",
  "pen": "images/pen.png",
  "pet": "images/pet.png",
  "pig": "images/pig.png",
  "pin": "images/pin.png",
  "pit": "images/pit.png",
  "pop": "images/pop.png",
  "pot": "images/pot.png",
  "pug": "images/pug.png",
  "pup": "images/pup.png",
  "rag": "images/rag.png",
  "ram": "images/ram.png",
  "rat": "images/rat.png",
  "rib": "images/rib.png",
  "rig": "images/rig.png",
  "rim": "images/rim.png",
  "rip": "images/rip.png",
  "rob": "images/rob.png",
  "rod": "images/rod.png",
  "rug": "images/rug.png",
  "run": "images/run.png",
  "sad": "images/sad.png",
  "sap": "images/sap.png",
  "sip": "images/sip.png",
  "sit": "images/sit.png",
  "sob": "images/sob.png",
  "sub": "images/sub.png",
  "sun": "images/sun.png",
  "tag": "images/tag.png",
  "tap": "images/tap.png",
  "ten": "images/ten.png",
  "tin": "images/tin.png",
  "top": "images/top.png",
  "tub": "images/tub.png",
  "tug": "images/tug.png",
  "tux": "images/tux.png",
  "van": "images/van.png",
  "vet": "images/vet.png",
  "wag": "images/wag.png",
  "wax": "images/wax.png",
  "web": "images/web.png",
  "wed": "images/wed.png",
  "wig": "images/wig.png",
  "win": "images/win.png",
  "zap": "images/zap.png",
  "fox": "images/fox.png",
  "fix": "images/fix.png",
  "six": "images/six.png",
  "men": "images/men.png",
  "sax": "images/sax.png",
  "zip": "images/zip.png"
};
