// glued_sounds_full.js
// Ladders (6 words), patterns, and images for glued sounds.

const gluedWordLadders = [
  ["bang", "bonk", "honk", "hung", "hall", "hang"],
  ["bang", "bonk", "honk", "hung", "hall", "wall"],
  ["bang", "bonk", "honk", "hung", "hall", "fall"],
  ["bang", "bonk", "honk", "hung", "hall", "ball"],
  ["bang", "bonk", "honk", "hung", "hall", "tall"],
  ["bang", "bonk", "honk", "hung", "hall", "call"],
  ["bang", "bonk", "honk", "hung", "hall", "mall"],
  ["bang", "bonk", "honk", "hung", "rung", "rank"],
  ["bang", "bonk", "honk", "hung", "rung", "rang"],
  ["bang", "bonk", "honk", "hung", "rung", "rink"],
  ["bunk", "dunk", "ding", "sing", "ring", "king"],
  ["bunk", "dunk", "ding", "sing", "ring", "rink"],
  ["bunk", "dunk", "ding", "sing", "ring", "rung"],
  ["bunk", "dunk", "ding", "sing", "ring", "rank"],
  ["bunk", "dunk", "ding", "sing", "ring", "rang"],
  ["bunk", "dunk", "ding", "sing", "ring", "wing"],
  ["bunk", "dunk", "ding", "sing", "wing", "ring"],
  ["bunk", "dunk", "ding", "sing", "wing", "wall"],
  ["bunk", "dunk", "ding", "sing", "wing", "wink"],
  ["bunk", "dunk", "ding", "sing", "wing", "king"],
  ["thank", "yank", "rank", "rung", "hung", "hang"],
  ["thank", "yank", "rank", "rung", "hung", "hall"],
  ["thank", "yank", "rank", "rung", "hung", "lung"],
  ["thank", "yank", "rank", "rung", "hung", "honk"],
  ["thank", "yank", "rank", "rung", "lung", "link"],
  ["thank", "yank", "rank", "rung", "lung", "hung"],
  ["thank", "yank", "rank", "rung", "lung", "long"],
  ["thank", "yank", "rank", "rung", "rink", "think"],
  ["thank", "yank", "rank", "rung", "rink", "link"],
  ["thank", "yank", "rank", "rung", "rink", "pink"],
  ["ball", "tall", "mall", "fall", "call", "wall"],
  ["ball", "tall", "mall", "fall", "call", "hall"],
  ["ball", "tall", "mall", "fall", "hall", "call"],
  ["ball", "tall", "mall", "fall", "hall", "wall"],
  ["ball", "tall", "mall", "fall", "hall", "honk"],
  ["ball", "tall", "mall", "fall", "hall", "hung"],
  ["ball", "tall", "mall", "fall", "hall", "hang"],
  ["ball", "tall", "mall", "fall", "fang", "hang"],
  ["ball", "tall", "mall", "fall", "fang", "sang"],
  ["ball", "tall", "mall", "fall", "fang", "gang"],
  ["king", "sing", "ding", "dunk", "junk", "bunk"],
  ["king", "sing", "ding", "dunk", "bunk", "bank"],
  ["king", "sing", "ding", "dunk", "bunk", "bonk"],
  ["king", "sing", "ding", "dunk", "bunk", "junk"],
  ["king", "sing", "ding", "dunk", "bunk", "bang"],
  ["king", "sing", "ding", "dunk", "bunk", "ball"],
  ["king", "sing", "ding", "ring", "wing", "wall"],
  ["king", "sing", "ding", "ring", "wing", "wink"],
  ["king", "sing", "ding", "ring", "rank", "sank"],
  ["king", "sing", "ding", "ring", "rank", "rink"],
  ["mall", "wall", "call", "fall", "fang", "sang"],
  ["mall", "wall", "call", "fall", "fang", "gang"],
  ["mall", "wall", "call", "fall", "fang", "hang"],
  ["mall", "wall", "call", "fall", "fang", "rang"],
  ["mall", "wall", "call", "fall", "fang", "bang"],
  ["mall", "wall", "call", "fall", "tall", "hall"],
  ["mall", "wall", "call", "fall", "tall", "tank"],
  ["mall", "wall", "call", "fall", "tall", "ball"],
  ["mall", "wall", "call", "fall", "hall", "hung"],
  ["mall", "wall", "call", "fall", "hall", "hang"],
  ["yank", "tank", "thank", "bank", "bonk", "honk"],
  ["yank", "tank", "thank", "bank", "bonk", "bunk"],
  ["yank", "tank", "thank", "bank", "bonk", "ball"],
  ["yank", "tank", "thank", "bank", "bonk", "bang"],
  ["yank", "tank", "thank", "bank", "ball", "bonk"],
  ["yank", "tank", "thank", "bank", "ball", "fall"],
  ["yank", "tank", "thank", "bank", "ball", "wall"],
  ["yank", "tank", "thank", "bank", "ball", "tall"],
  ["yank", "tank", "thank", "bank", "ball", "bang"],
  ["yank", "tank", "thank", "bank", "ball", "call"],
  ["hung", "rung", "rang", "hang", "honk", "hall"],
  ["hung", "rung", "rang", "hang", "honk", "bonk"],
  ["hung", "rung", "rang", "hang", "gang", "gong"],
  ["hung", "rung", "rang", "hang", "gang", "bang"],
  ["hung", "rung", "rang", "hang", "gang", "fang"],
  ["hung", "rung", "rang", "hang", "gang", "sang"],
  ["hung", "rung", "rang", "hang", "fang", "bang"],
  ["hung", "rung", "rang", "hang", "fang", "fall"],
  ["hung", "rung", "rang", "hang", "fang", "gang"],
  ["hung", "rung", "rang", "hang", "fang", "sang"],
  ["hang", "hall", "ball", "bank", "thank", "tank"],
  ["hang", "hall", "ball", "bank", "thank", "yank"],
  ["hang", "hall", "ball", "bank", "thank", "sank"],
  ["hang", "hall", "ball", "bank", "thank", "rank"],
  ["hang", "hall", "ball", "bank", "thank", "think"],
  ["hang", "hall", "ball", "bank", "bunk", "bonk"],
  ["hang", "hall", "ball", "bank", "bunk", "dunk"],
  ["hang", "hall", "ball", "bank", "bunk", "bang"],
  ["hang", "hall", "ball", "bank", "bunk", "junk"],
  ["hang", "hall", "ball", "bank", "yank", "tank"],
  ["gang", "gong", "song", "sank", "bank", "yank"],
  ["gang", "gong", "song", "sank", "bank", "bang"],
  ["gang", "gong", "song", "sank", "bank", "thank"],
  ["gang", "gong", "song", "sank", "bank", "rank"],
  ["gang", "gong", "song", "sank", "bank", "bonk"],
  ["gang", "gong", "song", "sank", "bank", "bunk"],
  ["gang", "gong", "song", "sank", "bank", "ball"],
  ["gang", "gong", "song", "sank", "bank", "tank"],
  ["gang", "gong", "song", "sank", "sing", "ding"],
  ["gang", "gong", "song", "sank", "sing", "ring"],
  ["bank", "ball", "tall", "wall", "mall", "fall"],
  ["bank", "ball", "tall", "wall", "mall", "hall"],
  ["bank", "ball", "tall", "wall", "mall", "call"],
  ["bank", "ball", "tall", "wall", "fall", "mall"],
  ["bank", "ball", "tall", "wall", "fall", "hall"],
  ["bank", "ball", "tall", "wall", "fall", "fang"],
  ["bank", "ball", "tall", "wall", "fall", "call"],
  ["bank", "ball", "tall", "wall", "wink", "rink"],
  ["bank", "ball", "tall", "wall", "wink", "pink"],
  ["bank", "ball", "tall", "wall", "wink", "think"],
  ["wink", "rink", "rank", "yank", "sank", "song"],
  ["wink", "rink", "rank", "yank", "sank", "thank"],
  ["wink", "rink", "rank", "yank", "sank", "tank"],
  ["wink", "rink", "rank", "yank", "sank", "sang"],
  ["wink", "rink", "rank", "yank", "sank", "sink"],
  ["wink", "rink", "rank", "yank", "sank", "sing"],
  ["wink", "rink", "rank", "yank", "sank", "bank"],
  ["wink", "rink", "rank", "yank", "tank", "thank"],
  ["wink", "rink", "rank", "yank", "tank", "bank"],
  ["wink", "rink", "rank", "yank", "tank", "tall"],
  ["gong", "song", "sink", "wink", "pink", "rink"],
  ["gong", "song", "sink", "wink", "pink", "link"],
  ["gong", "song", "sink", "wink", "pink", "think"],
  ["gong", "song", "sink", "wink", "wall", "ball"],
  ["gong", "song", "sink", "wink", "wall", "hall"],
  ["gong", "song", "sink", "wink", "wall", "tall"],
  ["gong", "song", "sink", "wink", "wall", "mall"],
  ["gong", "song", "sink", "wink", "wall", "fall"],
  ["gong", "song", "sink", "wink", "wall", "wing"],
  ["gong", "song", "sink", "wink", "wall", "call"],
  ["honk", "hung", "hall", "tall", "call", "fall"],
  ["honk", "hung", "hall", "tall", "call", "ball"],
  ["honk", "hung", "hall", "tall", "call", "wall"],
  ["honk", "hung", "hall", "tall", "call", "mall"],
  ["honk", "hung", "hall", "tall", "wall", "wink"],
  ["honk", "hung", "hall", "tall", "wall", "mall"],
  ["honk", "hung", "hall", "tall", "wall", "ball"],
  ["honk", "hung", "hall", "tall", "wall", "call"],
  ["honk", "hung", "hall", "tall", "wall", "fall"],
  ["honk", "hung", "hall", "tall", "wall", "wing"],
  ["junk", "dunk", "ding", "king", "ring", "rang"],
  ["junk", "dunk", "ding", "king", "ring", "rung"],
  ["junk", "dunk", "ding", "king", "ring", "rank"],
  ["junk", "dunk", "ding", "king", "ring", "sing"],
  ["junk", "dunk", "ding", "king", "ring", "wing"],
  ["junk", "dunk", "ding", "king", "ring", "rink"],
  ["junk", "dunk", "ding", "king", "wing", "sing"],
  ["junk", "dunk", "ding", "king", "wing", "ring"],
  ["junk", "dunk", "ding", "king", "wing", "wall"],
  ["junk", "dunk", "ding", "king", "wing", "wink"],
  ["ding", "sing", "song", "long", "gong", "gang"],
  ["ding", "sing", "song", "long", "link", "pink"],
  ["ding", "sing", "song", "long", "link", "think"],
  ["ding", "sing", "song", "long", "link", "wink"],
  ["ding", "sing", "song", "long", "link", "sink"],
  ["ding", "sing", "song", "long", "link", "rink"],
  ["ding", "sing", "song", "long", "link", "lung"],
  ["ding", "sing", "song", "long", "lung", "rung"],
  ["ding", "sing", "song", "long", "lung", "hung"],
  ["ding", "sing", "song", "long", "lung", "link"],
  ["call", "tall", "hall", "hang", "fang", "gang"],
  ["call", "tall", "hall", "hang", "fang", "bang"],
  ["call", "tall", "hall", "hang", "fang", "fall"],
  ["call", "tall", "hall", "hang", "fang", "sang"],
  ["call", "tall", "hall", "hang", "fang", "rang"],
  ["call", "tall", "hall", "hang", "bang", "gang"],
  ["call", "tall", "hall", "hang", "bang", "sang"],
  ["call", "tall", "hall", "hang", "bang", "bunk"],
  ["call", "tall", "hall", "hang", "bang", "fang"],
  ["call", "tall", "hall", "hang", "bang", "rang"],
  ["sang", "fang", "rang", "ring", "king", "sing"],
  ["sang", "fang", "rang", "ring", "king", "ding"],
  ["sang", "fang", "rang", "ring", "king", "wing"],
  ["sang", "fang", "rang", "ring", "wing", "king"],
  ["sang", "fang", "rang", "ring", "wing", "wall"],
  ["sang", "fang", "rang", "ring", "wing", "ding"],
  ["sang", "fang", "rang", "ring", "wing", "wink"],
  ["sang", "fang", "rang", "ring", "wing", "sing"],
  ["sang", "fang", "rang", "ring", "sing", "ding"],
  ["sang", "fang", "rang", "ring", "sing", "king"],
  ["hall", "fall", "mall", "ball", "call", "tall"],
  ["hall", "fall", "mall", "ball", "call", "wall"],
  ["hall", "fall", "mall", "ball", "bunk", "bonk"],
  ["hall", "fall", "mall", "ball", "bunk", "dunk"],
  ["hall", "fall", "mall", "ball", "bunk", "junk"],
  ["hall", "fall", "mall", "ball", "bunk", "bang"],
  ["hall", "fall", "mall", "ball", "bunk", "bank"],
  ["hall", "fall", "mall", "ball", "wall", "wink"],
  ["hall", "fall", "mall", "ball", "wall", "call"],
  ["hall", "fall", "mall", "ball", "wall", "tall"],
  ["lung", "long", "gong", "gang", "fang", "fall"],
  ["lung", "long", "gong", "gang", "fang", "hang"],
  ["lung", "long", "gong", "gang", "fang", "sang"],
  ["lung", "long", "gong", "gang", "fang", "bang"],
  ["lung", "long", "gong", "gang", "fang", "rang"],
  ["lung", "long", "gong", "gang", "sang", "sank"],
  ["lung", "long", "gong", "gang", "sang", "rang"],
  ["lung", "long", "gong", "gang", "sang", "fang"],
  ["lung", "long", "gong", "gang", "sang", "sing"],
  ["lung", "long", "gong", "gang", "sang", "sink"],
  ["tank", "sank", "song", "sink", "think", "pink"],
  ["tank", "sank", "song", "sink", "think", "rink"],
  ["tank", "sank", "song", "sink", "think", "link"],
  ["tank", "sank", "song", "sink", "think", "thank"],
  ["tank", "sank", "song", "sink", "think", "wink"],
  ["tank", "sank", "song", "sink", "pink", "rink"],
  ["tank", "sank", "song", "sink", "pink", "wink"],
  ["tank", "sank", "song", "sink", "pink", "think"],
  ["tank", "sank", "song", "sink", "pink", "link"],
  ["tank", "sank", "song", "sink", "link", "think"],
  ["tall", "fall", "ball", "bang", "sang", "rang"],
  ["tall", "fall", "ball", "bang", "sang", "sink"],
  ["tall", "fall", "ball", "bang", "sang", "song"],
  ["tall", "fall", "ball", "bang", "sang", "hang"],
  ["tall", "fall", "ball", "bang", "sang", "sank"],
  ["tall", "fall", "ball", "bang", "sang", "sing"],
  ["tall", "fall", "ball", "bang", "sang", "fang"],
  ["tall", "fall", "ball", "bang", "sang", "gang"],
  ["tall", "fall", "ball", "bang", "bonk", "bunk"],
  ["tall", "fall", "ball", "bang", "bonk", "honk"],
  ["rink", "sink", "think", "pink", "wink", "link"],
  ["rink", "sink", "think", "pink", "wink", "wall"],
  ["rink", "sink", "think", "pink", "wink", "wing"],
  ["rink", "sink", "think", "pink", "link", "wink"],
  ["rink", "sink", "think", "pink", "link", "long"],
  ["rink", "sink", "think", "pink", "link", "lung"],
  ["rink", "sink", "think", "wink", "link", "long"],
  ["rink", "sink", "think", "wink", "link", "pink"],
  ["rink", "sink", "think", "wink", "link", "lung"],
  ["rink", "sink", "think", "wink", "wall", "wing"],
  ["link", "think", "sink", "pink", "rink", "rung"],
  ["link", "think", "sink", "pink", "rink", "rank"],
  ["link", "think", "sink", "pink", "rink", "wink"],
  ["link", "think", "sink", "pink", "rink", "rang"],
  ["link", "think", "sink", "pink", "rink", "ring"],
  ["link", "think", "sink", "pink", "wink", "wing"],
  ["link", "think", "sink", "pink", "wink", "wall"],
  ["link", "think", "sink", "pink", "wink", "rink"],
  ["link", "think", "sink", "wink", "rink", "pink"],
  ["link", "think", "sink", "wink", "rink", "rang"],
  ["pink", "rink", "rung", "hung", "lung", "long"],
  ["pink", "rink", "rung", "hung", "lung", "link"],
  ["pink", "rink", "rung", "hung", "honk", "hang"],
  ["pink", "rink", "rung", "hung", "honk", "hall"],
  ["pink", "rink", "rung", "hung", "honk", "bonk"],
  ["pink", "rink", "rung", "hung", "hang", "honk"],
  ["pink", "rink", "rung", "hung", "hang", "rang"],
  ["pink", "rink", "rung", "hung", "hang", "sang"],
  ["pink", "rink", "rung", "hung", "hang", "gang"],
  ["pink", "rink", "rung", "hung", "hang", "hall"],
  ["bonk", "honk", "hang", "gang", "sang", "sank"],
  ["bonk", "honk", "hang", "gang", "sang", "sing"],
  ["bonk", "honk", "hang", "gang", "sang", "bang"],
  ["bonk", "honk", "hang", "gang", "sang", "fang"],
  ["bonk", "honk", "hang", "gang", "sang", "sink"],
  ["bonk", "honk", "hang", "gang", "sang", "song"],
  ["bonk", "honk", "hang", "gang", "sang", "rang"],
  ["bonk", "honk", "hang", "gang", "rang", "rung"],
  ["bonk", "honk", "hang", "gang", "rang", "fang"],
  ["bonk", "honk", "hang", "gang", "rang", "sang"],
  ["fang", "rang", "rink", "sink", "sank", "tank"],
  ["fang", "rang", "rink", "sink", "sank", "rank"],
  ["fang", "rang", "rink", "sink", "sank", "bank"],
  ["fang", "rang", "rink", "sink", "sank", "yank"],
  ["fang", "rang", "rink", "sink", "sank", "song"],
  ["fang", "rang", "rink", "sink", "sank", "thank"],
  ["fang", "rang", "rink", "sink", "sank", "sang"],
  ["fang", "rang", "rink", "sink", "sank", "sing"],
  ["fang", "rang", "rink", "sink", "link", "wink"],
  ["fang", "rang", "rink", "sink", "link", "lung"],
  ["think", "pink", "sink", "rink", "ring", "sing"],
  ["think", "pink", "sink", "rink", "ring", "ding"],
  ["think", "pink", "sink", "rink", "ring", "rank"],
  ["think", "pink", "sink", "rink", "ring", "rang"],
  ["think", "pink", "sink", "rink", "ring", "wing"],
  ["think", "pink", "sink", "rink", "ring", "king"],
  ["think", "pink", "sink", "rink", "ring", "rung"],
  ["think", "pink", "sink", "rink", "rung", "rang"],
  ["think", "pink", "sink", "rink", "rung", "rank"],
  ["think", "pink", "sink", "rink", "rung", "lung"],
  ["wing", "ding", "dunk", "bunk", "bank", "yank"],
  ["wing", "ding", "dunk", "bunk", "bank", "sank"],
  ["wing", "ding", "dunk", "bunk", "bank", "tank"],
  ["wing", "ding", "dunk", "bunk", "bank", "thank"],
  ["wing", "ding", "dunk", "bunk", "bank", "rank"],
  ["wing", "ding", "dunk", "bunk", "bank", "bang"],
  ["wing", "ding", "dunk", "bunk", "bank", "ball"],
  ["wing", "ding", "dunk", "bunk", "bank", "bonk"],
  ["wing", "ding", "dunk", "bunk", "bang", "bank"],
  ["wing", "ding", "dunk", "bunk", "bang", "rang"],
  ["long", "song", "sink", "sing", "wing", "wall"],
  ["long", "song", "sink", "sing", "wing", "king"],
  ["long", "song", "sink", "sing", "wing", "wink"],
  ["long", "song", "sink", "sing", "wing", "ding"],
  ["long", "song", "sink", "sing", "wing", "ring"],
  ["long", "song", "sink", "sing", "sank", "tank"],
  ["long", "song", "sink", "sing", "sank", "sang"],
  ["long", "song", "sink", "sing", "sank", "thank"],
  ["long", "song", "sink", "sing", "sank", "bank"],
  ["long", "song", "sink", "sing", "sank", "rank"],
  ["ring", "rank", "rink", "wink", "think", "pink"],
  ["ring", "rank", "rink", "wink", "think", "link"],
  ["ring", "rank", "rink", "wink", "think", "thank"],
  ["ring", "rank", "rink", "wink", "think", "sink"],
  ["ring", "rank", "rink", "wink", "sink", "think"],
  ["ring", "rank", "rink", "wink", "sink", "song"],
  ["ring", "rank", "rink", "wink", "sink", "sank"],
  ["ring", "rank", "rink", "wink", "sink", "pink"],
  ["ring", "rank", "rink", "wink", "sink", "sang"],
  ["ring", "rank", "rink", "wink", "sink", "link"],
  ["sink", "sang", "fang", "hang", "hall", "honk"],
  ["sink", "sang", "fang", "hang", "hall", "fall"],
  ["sink", "sang", "fang", "hang", "hall", "mall"],
  ["sink", "sang", "fang", "hang", "hall", "wall"],
  ["sink", "sang", "fang", "hang", "hall", "call"],
  ["sink", "sang", "fang", "hang", "hall", "tall"],
  ["sink", "sang", "fang", "hang", "hall", "ball"],
  ["sink", "sang", "fang", "hang", "hall", "hung"],
  ["sink", "sang", "fang", "hang", "bang", "rang"],
  ["sink", "sang", "fang", "hang", "bang", "gang"],
  ["dunk", "ding", "wing", "wink", "rink", "sink"],
  ["dunk", "ding", "wing", "wink", "rink", "rung"],
  ["dunk", "ding", "wing", "wink", "rink", "link"],
  ["dunk", "ding", "wing", "wink", "rink", "pink"],
  ["dunk", "ding", "wing", "wink", "rink", "ring"],
  ["dunk", "ding", "wing", "wink", "rink", "think"],
  ["dunk", "ding", "wing", "wink", "rink", "rang"],
  ["dunk", "ding", "wing", "wink", "rink", "rank"],
  ["dunk", "ding", "wing", "wink", "think", "link"],
  ["dunk", "ding", "wing", "wink", "think", "sink"],
  ["song", "sink", "link", "pink", "think", "wink"],
  ["song", "sink", "link", "pink", "think", "thank"],
  ["song", "sink", "link", "pink", "think", "rink"],
  ["song", "sink", "link", "pink", "wink", "wall"],
  ["song", "sink", "link", "pink", "wink", "think"],
  ["song", "sink", "link", "pink", "wink", "rink"],
  ["song", "sink", "link", "pink", "wink", "wing"],
  ["song", "sink", "link", "pink", "rink", "ring"],
  ["song", "sink", "link", "pink", "rink", "rung"],
  ["song", "sink", "link", "pink", "rink", "wink"],
  ["sing", "sang", "sank", "thank", "tank", "rank"],
  ["sing", "sang", "sank", "thank", "tank", "tall"],
  ["sing", "sang", "sank", "thank", "tank", "yank"],
  ["sing", "sang", "sank", "thank", "tank", "bank"],
  ["sing", "sang", "sank", "thank", "yank", "rank"],
  ["sing", "sang", "sank", "thank", "yank", "tank"],
  ["sing", "sang", "sank", "thank", "yank", "bank"],
  ["sing", "sang", "sank", "thank", "think", "sink"],
  ["sing", "sang", "sank", "thank", "think", "pink"],
  ["sing", "sang", "sank", "thank", "think", "link"],
  ["rank", "sank", "sink", "pink", "wink", "link"],
  ["rank", "sank", "sink", "pink", "wink", "rink"],
  ["rank", "sank", "sink", "pink", "wink", "think"],
  ["rank", "sank", "sink", "pink", "wink", "wing"],
  ["rank", "sank", "sink", "pink", "wink", "wall"],
  ["rank", "sank", "sink", "pink", "link", "lung"],
  ["rank", "sank", "sink", "pink", "link", "wink"],
  ["rank", "sank", "sink", "pink", "link", "rink"],
  ["rank", "sank", "sink", "pink", "link", "think"],
  ["rank", "sank", "sink", "pink", "link", "long"],
  ["sank", "song", "sing", "ding", "ring", "king"],
  ["sank", "song", "sing", "ding", "ring", "rink"],
  ["sank", "song", "sing", "ding", "ring", "rang"],
  ["sank", "song", "sing", "ding", "ring", "rung"],
  ["sank", "song", "sing", "ding", "ring", "wing"],
  ["sank", "song", "sing", "ding", "ring", "rank"],
  ["sank", "song", "sing", "ding", "dunk", "bunk"],
  ["sank", "song", "sing", "ding", "dunk", "junk"],
  ["sank", "song", "sing", "ding", "king", "ring"],
  ["sank", "song", "sing", "ding", "king", "wing"],
  ["rang", "sang", "hang", "gang", "gong", "long"],
  ["rang", "sang", "hang", "gang", "gong", "song"],
  ["rang", "sang", "hang", "gang", "bang", "ball"],
  ["rang", "sang", "hang", "gang", "bang", "bonk"],
  ["rang", "sang", "hang", "gang", "bang", "bunk"],
  ["rang", "sang", "hang", "gang", "bang", "fang"],
  ["rang", "sang", "hang", "gang", "bang", "bank"],
  ["rang", "sang", "hang", "gang", "fang", "fall"],
  ["rang", "sang", "hang", "gang", "fang", "bang"],
  ["rang", "sang", "hang", "hall", "wall", "tall"],
  ["wall", "fall", "mall", "hall", "honk", "hung"],
  ["wall", "fall", "mall", "hall", "honk", "hang"],
  ["wall", "fall", "mall", "hall", "honk", "bonk"],
  ["wall", "fall", "mall", "hall", "hung", "rung"],
  ["wall", "fall", "mall", "hall", "hung", "hang"],
  ["wall", "fall", "mall", "hall", "hung", "honk"],
  ["wall", "fall", "mall", "hall", "hung", "lung"],
  ["wall", "fall", "mall", "hall", "call", "tall"],
  ["wall", "fall", "mall", "hall", "call", "ball"],
  ["wall", "fall", "mall", "hall", "tall", "ball"],
  ["fall", "tall", "mall", "hall", "ball", "bonk"],
  ["fall", "tall", "mall", "hall", "ball", "bunk"],
  ["fall", "tall", "mall", "hall", "ball", "bank"],
  ["fall", "tall", "mall", "hall", "ball", "bang"],
  ["fall", "tall", "mall", "hall", "ball", "wall"],
  ["fall", "tall", "mall", "hall", "ball", "call"],
  ["fall", "tall", "mall", "hall", "call", "ball"],
  ["fall", "tall", "mall", "hall", "call", "wall"],
  ["fall", "tall", "mall", "hall", "hang", "rang"],
  ["fall", "tall", "mall", "hall", "hang", "hung"],
  ["rung", "rang", "bang", "hang", "sang", "song"],
  ["rung", "rang", "bang", "hang", "sang", "sink"],
  ["rung", "rang", "bang", "hang", "sang", "sing"],
  ["rung", "rang", "bang", "hang", "sang", "gang"],
  ["rung", "rang", "bang", "hang", "sang", "fang"],
  ["rung", "rang", "bang", "hang", "sang", "sank"],
  ["rung", "rang", "bang", "hang", "honk", "hung"],
  ["rung", "rang", "bang", "hang", "honk", "hall"],
  ["rung", "rang", "bang", "hang", "honk", "bonk"],
  ["rung", "rang", "bang", "hang", "hung", "honk"],
];

const gluedWordPatterns = {
  "all": "3",
  "ball": "13",
  "bang": "13",
  "bank": "13",
  "bonk": "13",
  "bunk": "13",
  "call": "13",
  "ding": "13",
  "dunk": "13",
  "fall": "13",
  "fang": "13",
  "gang": "13",
  "gong": "13",
  "hall": "13",
  "hang": "13",
  "honk": "13",
  "hung": "13",
  "junk": "13",
  "king": "13",
  "link": "13",
  "long": "13",
  "lung": "13",
  "mall": "13",
  "pink": "13",
  "rang": "13",
  "rank": "13",
  "ring": "13",
  "rink": "13",
  "rung": "13",
  "sang": "13",
  "sank": "13",
  "sing": "13",
  "sink": "13",
  "song": "13",
  "tall": "13",
  "tank": "13",
  "thank": "23",
  "think": "23",
  "wall": "13",
  "wing": "13",
  "wink": "13",
  "yank": "13"
};

const gluedWordImages = {
  "all": "images/all.png",
  "ball": "images/ball.png",
  "bang": "images/bang.png",
  "bank": "images/bank.png",
  "bonk": "images/bonk.png",
  "bunk": "images/bunk.png",
  "call": "images/call.png",
  "ding": "images/ding.png",
  "dunk": "images/dunk.png",
  "fall": "images/fall.png",
  "fang": "images/fang.png",
  "gang": "images/gang.png",
  "gong": "images/gong.png",
  "hall": "images/hall.png",
  "hang": "images/hang.png",
  "honk": "images/honk.png",
  "hung": "images/hung.png",
  "junk": "images/junk.png",
  "king": "images/king.png",
  "link": "images/link.png",
  "long": "images/long.png",
  "lung": "images/lung.png",
  "mall": "images/mall.png",
  "pink": "images/pink.png",
  "rang": "images/rang.png",
  "rank": "images/rank.png",
  "ring": "images/ring.png",
  "rink": "images/rink.png",
  "rung": "images/rung.png",
  "sang": "images/sang.png",
  "sank": "images/sank.png",
  "sing": "images/sing.png",
  "sink": "images/sink.png",
  "song": "images/song.png",
  "tall": "images/tall.png",
  "tank": "images/tank.png",
  "thank": "images/thank.png",
  "think": "images/think.png",
  "wall": "images/wall.png",
  "wing": "images/wing.png",
  "wink": "images/wink.png",
  "yank": "images/yank.png"
};
