// ==== Long E Words + Ladders (auto-generated) ====
// One change per step (letter or vowel team), ladders capped at 5 per start

const longE_words = [
  { word: "bee", pattern: "12", split: ["b", "ee"] },
  { word: "fee", pattern: "12", split: ["f", "ee"] },
  { word: "see", pattern: "12", split: ["s", "ee"] },
  { word: "sheep", pattern: "221", split: ["sh", "ee", "p"] },
  { word: "beep", pattern: "121", split: ["b", "ee", "p"] },
  { word: "beet", pattern: "121", split: ["b", "ee", "t"] },
  { word: "flee", pattern: "112", split: ["fl", "ee"] },
  { word: "queen", pattern: "221", split: ["qu", "ee", "n"] },
  { word: "sheet", pattern: "221", split: ["sh", "ee", "t"] },
  { word: "cheek", pattern: "221", split: ["ch", "ee", "k"] },
  { word: "deep", pattern: "121", split: ["d", "ee", "p"] },
  { word: "seek", pattern: "121", split: ["s", "ee", "k"] },
  { word: "week", pattern: "121", split: ["w", "ee", "k"] },
  { word: "peel", pattern: "121", split: ["p", "ee", "l"] },
  { word: "feel", pattern: "121", split: ["f", "ee", "l"] },
  { word: "eel", pattern: "21", split: ["ee", "l"] },
  { word: "teeth", pattern: "122", split: ["t", "ee", "th"] },
  { word: "weep", pattern: "121", split: ["w", "ee", "p"] },
  { word: "meet", pattern: "121", split: ["m", "ee", "t"] },
  { word: "feed", pattern: "121", split: ["f", "ee", "d"] },
  { word: "peek", pattern: "121", split: ["p", "ee", "k"] },
  { word: "bleed", pattern: "1121", split: ["bl", "ee", "d"] },
  { word: "breeze", pattern: "1122", split: ["br", "ee", "ze"] },
  { word: "creek", pattern: "1121", split: ["cr", "ee", "k"] },
  { word: "creep", pattern: "1121", split: ["cr", "ee", "p"] },
  { word: "speed", pattern: "1121", split: ["sp", "ee", "d"] },
  { word: "speech", pattern: "1122", split: ["sp", "ee", "ch"] },
  { word: "steel", pattern: "1121", split: ["st", "ee", "l"] },
  { word: "steep", pattern: "1121", split: ["st", "ee", "p"] },
  { word: "sweep", pattern: "1121", split: ["sw", "ee", "p"] },
  { word: "sweet", pattern: "1121", split: ["sw", "ee", "t"] },
  { word: "three", pattern: "212", split: ["thr", "ee"] },
  { word: "fleet", pattern: "1121", split: ["fl", "ee", "t"] },
  { word: "street", pattern: "11121", split: ["str", "ee", "t"] },
  { word: "pea", pattern: "12", split: ["p", "ea"] },
  { word: "sea", pattern: "12", split: ["s", "ea"] },
  { word: "tea", pattern: "12", split: ["t", "ea"] },
  { word: "bead", pattern: "121", split: ["b", "ea", "d"] },
  { word: "beam", pattern: "121", split: ["b", "ea", "m"] },
  { word: "bean", pattern: "121", split: ["b", "ea", "n"] },
  { word: "beat", pattern: "121", split: ["b", "ea", "t"] },
  { word: "beak", pattern: "121", split: ["b", "ea", "k"] },
  { word: "heat", pattern: "121", split: ["h", "ea", "t"] },
  { word: "lean", pattern: "121", split: ["l", "ea", "n"] },
  { word: "leap", pattern: "121", split: ["l", "ea", "p"] },
  { word: "meat", pattern: "121", split: ["m", "ea", "t"] },
  { word: "read", pattern: "121", split: ["r", "ea", "d"] },
  { word: "seat", pattern: "121", split: ["s", "ea", "t"] },
  { word: "seal", pattern: "121", split: ["s", "ea", "l"] },
  { word: "reach", pattern: "122", split: ["r", "ea", "ch"] },
  { word: "beach", pattern: "122", split: ["b", "ea", "ch"] },
  { word: "peach", pattern: "122", split: ["p", "ea", "ch"] },
  { word: "cheap", pattern: "221", split: ["ch", "ea", "p"] },
  { word: "wheel", pattern: "221", split: ["wh", "ee", "l"] },
  { word: "bleak", pattern: "1121", split: ["bl", "ea", "k"] },
  { word: "clean", pattern: "1121", split: ["cl", "ea", "n"] },
  { word: "cream", pattern: "1121", split: ["cr", "ea", "m"] },
  { word: "creak", pattern: "1121", split: ["cr", "ea", "k"] },
  { word: "dream", pattern: "1121", split: ["dr", "ea", "m"] },
  { word: "steal", pattern: "1121", split: ["st", "ea", "l"] },
  { word: "steam", pattern: "1121", split: ["st", "ea", "m"] },
  { word: "treat", pattern: "1121", split: ["tr", "ea", "t"] },
  { word: "screech", pattern: "11122", split: ["scr", "ee", "ch"] },
  { word: "squeak", pattern: "1221", split: ["sq", "ue", "ak"] },
  { word: "scream", pattern: "11121", split: ["scr", "ea", "m"] },
  { word: "spleen", pattern: "11121", split: ["spl", "ee", "n"] },
  { word: "streak", pattern: "11121", split: ["str", "ea", "k"] },
];

const longEWordLadders = [
  ["beach", "reach", "read", "bead", "beat", "seat"],
  ["beach", "reach", "read", "bead", "beat", "meat"],
  ["beach", "reach", "read", "bead", "beat", "heat"],
  ["beach", "reach", "read", "bead", "beat", "beet"],
  ["beach", "reach", "read", "bead", "beat", "bean"],
  ["bead", "read", "reach", "peach", "beach", "beat"],
  ["bead", "read", "reach", "peach", "beach", "bean"],
  ["bead", "read", "reach", "peach", "beach", "beam"],
  ["bead", "read", "reach", "peach", "beach", "beak"],
  ["bead", "read", "reach", "beach", "beat", "seat"],
  ["beak", "beat", "seat", "meat", "meet", "sheet"],
  ["beak", "beat", "seat", "meat", "meet", "beet"],
  ["beak", "beat", "seat", "heat", "meat", "meet"],
  ["beak", "beat", "meat", "meet", "sheet", "sheep"],
  ["beak", "beat", "meat", "meet", "sheet", "beet"],
  ["beam", "beat", "seat", "meat", "meet", "sheet"],
  ["beam", "beat", "seat", "meat", "meet", "beet"],
  ["beam", "beat", "seat", "heat", "meat", "meet"],
  ["beam", "beat", "meat", "meet", "sheet", "sheep"],
  ["beam", "beat", "meat", "meet", "sheet", "beet"],
  ["bean", "beat", "seat", "meat", "meet", "sheet"],
  ["bean", "beat", "seat", "meat", "meet", "beet"],
  ["bean", "beat", "seat", "heat", "meat", "meet"],
  ["bean", "beat", "meat", "meet", "sheet", "sheep"],
  ["bean", "beat", "meat", "meet", "sheet", "beet"],
  ["beat", "seat", "meat", "meet", "sheet", "sheep"],
  ["beat", "seat", "meat", "meet", "sheet", "beet"],
  ["beat", "seat", "meat", "meet", "beet", "sheet"],
  ["beat", "seat", "meat", "meet", "beet", "beep"],
  ["beat", "seat", "heat", "meat", "meet", "sheet"],
  ["bee", "fee", "see", "sea", "tea", "pea"],
  ["bee", "fee", "see", "sea", "pea", "tea"],
  ["beep", "weep", "week", "seek", "peek", "peel"],
  ["beep", "weep", "week", "seek", "peek", "cheek"],
  ["beep", "weep", "week", "seek", "cheek", "peek"],
  ["beep", "weep", "week", "peek", "seek", "cheek"],
  ["beep", "weep", "week", "peek", "peel", "wheel"],
  ["beet", "sheet", "sheep", "weep", "week", "seek"],
  ["beet", "sheet", "sheep", "weep", "week", "peek"],
  ["beet", "sheet", "sheep", "weep", "week", "cheek"],
  ["beet", "sheet", "sheep", "weep", "deep", "beep"],
  ["beet", "sheet", "sheep", "weep", "beep", "deep"],
  ["cheap", "leap", "lean", "bean", "beat", "seat"],
  ["cheap", "leap", "lean", "bean", "beat", "meat"],
  ["cheap", "leap", "lean", "bean", "beat", "heat"],
  ["cheap", "leap", "lean", "bean", "beat", "beet"],
  ["cheap", "leap", "lean", "bean", "beat", "beam"],
  ["cheek", "week", "weep", "sheep", "sheet", "meet"],
  ["cheek", "week", "weep", "sheep", "sheet", "beet"],
  ["cheek", "week", "weep", "sheep", "deep", "beep"],
  ["cheek", "week", "weep", "sheep", "beep", "deep"],
  ["cheek", "week", "weep", "sheep", "beep", "beet"],
  ["deep", "weep", "week", "seek", "peek", "peel"],
  ["deep", "weep", "week", "seek", "peek", "cheek"],
  ["deep", "weep", "week", "seek", "cheek", "peek"],
  ["deep", "weep", "week", "peek", "seek", "cheek"],
  ["deep", "weep", "week", "peek", "peel", "wheel"],
  ["fee", "bee", "see", "sea", "tea", "pea"],
  ["fee", "bee", "see", "sea", "pea", "tea"],
  ["feed", "feel", "wheel", "peel", "peek", "week"],
  ["feed", "feel", "wheel", "peel", "peek", "seek"],
  ["feed", "feel", "wheel", "peel", "peek", "cheek"],
  ["feed", "feel", "peel", "peek", "week", "weep"],
  ["feed", "feel", "peel", "peek", "week", "seek"],
  ["feel", "wheel", "peel", "peek", "week", "weep"],
  ["feel", "wheel", "peel", "peek", "week", "seek"],
  ["feel", "wheel", "peel", "peek", "week", "cheek"],
  ["feel", "wheel", "peel", "peek", "seek", "week"],
  ["feel", "wheel", "peel", "peek", "seek", "cheek"],
  ["heat", "seat", "meat", "meet", "sheet", "sheep"],
  ["heat", "seat", "meat", "meet", "sheet", "beet"],
  ["heat", "seat", "meat", "meet", "beet", "sheet"],
  ["heat", "seat", "meat", "meet", "beet", "beep"],
  ["heat", "seat", "meat", "meet", "beet", "beat"],
  ["lean", "bean", "beat", "seat", "meat", "meet"],
  ["lean", "bean", "beat", "seat", "meat", "heat"],
  ["lean", "bean", "beat", "seat", "heat", "meat"],
  ["lean", "bean", "beat", "meat", "seat", "seal"],
  ["lean", "bean", "beat", "meat", "seat", "heat"],
  ["leap", "lean", "bean", "beat", "seat", "seal"],
  ["leap", "lean", "bean", "beat", "seat", "meat"],
  ["leap", "lean", "bean", "beat", "seat", "heat"],
  ["leap", "lean", "bean", "beat", "meat", "seat"],
  ["leap", "lean", "bean", "beat", "meat", "meet"],
  ["meat", "seat", "heat", "beat", "beet", "sheet"],
  ["meat", "seat", "heat", "beat", "beet", "meet"],
  ["meat", "seat", "heat", "beat", "beet", "beep"],
  ["meat", "seat", "heat", "beat", "bean", "lean"],
  ["meat", "seat", "heat", "beat", "bean", "beam"],
  ["meet", "sheet", "sheep", "weep", "week", "seek"],
  ["meet", "sheet", "sheep", "weep", "week", "peek"],
  ["meet", "sheet", "sheep", "weep", "week", "cheek"],
  ["meet", "sheet", "sheep", "weep", "deep", "beep"],
  ["meet", "sheet", "sheep", "weep", "beep", "deep"],
  ["pea", "tea", "sea", "see", "fee", "bee"],
  ["pea", "tea", "sea", "see", "bee", "fee"],
  ["peach", "reach", "read", "bead", "beat", "seat"],
  ["peach", "reach", "read", "bead", "beat", "meat"],
  ["peach", "reach", "read", "bead", "beat", "heat"],
  ["peach", "reach", "read", "bead", "beat", "beet"],
  ["peach", "reach", "read", "bead", "beat", "bean"],
  ["peek", "week", "weep", "sheep", "sheet", "meet"],
  ["peek", "week", "weep", "sheep", "sheet", "beet"],
  ["peek", "week", "weep", "sheep", "deep", "beep"],
  ["peek", "week", "weep", "sheep", "beep", "deep"],
  ["peek", "week", "weep", "sheep", "beep", "beet"],
  ["peel", "peek", "week", "weep", "sheep", "sheet"],
  ["peel", "peek", "week", "weep", "sheep", "deep"],
  ["peel", "peek", "week", "weep", "sheep", "beep"],
  ["peel", "peek", "week", "weep", "deep", "sheep"],
  ["peel", "peek", "week", "weep", "deep", "beep"],
  ["reach", "read", "bead", "beat", "seat", "seal"],
  ["reach", "read", "bead", "beat", "seat", "meat"],
  ["reach", "read", "bead", "beat", "seat", "heat"],
  ["reach", "read", "bead", "beat", "meat", "seat"],
  ["reach", "read", "bead", "beat", "meat", "meet"],
  ["read", "reach", "peach", "beach", "beat", "seat"],
  ["read", "reach", "peach", "beach", "beat", "meat"],
  ["read", "reach", "peach", "beach", "beat", "heat"],
  ["read", "reach", "peach", "beach", "beat", "beet"],
  ["read", "reach", "peach", "beach", "beat", "bean"],
  ["seal", "seat", "meat", "meet", "sheet", "sheep"],
  ["seal", "seat", "meat", "meet", "sheet", "beet"],
  ["seal", "seat", "meat", "meet", "beet", "sheet"],
  ["seal", "seat", "meat", "meet", "beet", "beep"],
  ["seal", "seat", "meat", "meet", "beet", "beat"],
  ["seat", "meat", "meet", "sheet", "sheep", "weep"],
  ["seat", "meat", "meet", "sheet", "sheep", "deep"],
  ["seat", "meat", "meet", "sheet", "sheep", "beep"],
  ["seat", "meat", "meet", "sheet", "beet", "beep"],
  ["seat", "meat", "meet", "sheet", "beet", "beat"],
  ["seek", "week", "weep", "sheep", "sheet", "meet"],
  ["seek", "week", "weep", "sheep", "sheet", "beet"],
  ["seek", "week", "weep", "sheep", "deep", "beep"],
  ["seek", "week", "weep", "sheep", "beep", "deep"],
  ["seek", "week", "weep", "sheep", "beep", "beet"],
  ["sheep", "weep", "week", "seek", "peek", "peel"],
  ["sheep", "weep", "week", "seek", "peek", "cheek"],
  ["sheep", "weep", "week", "seek", "cheek", "peek"],
  ["sheep", "weep", "week", "peek", "seek", "cheek"],
  ["sheep", "weep", "week", "peek", "peel", "wheel"],
  ["sheet", "sheep", "weep", "week", "seek", "peek"],
  ["sheet", "sheep", "weep", "week", "seek", "cheek"],
  ["sheet", "sheep", "weep", "week", "peek", "seek"],
  ["sheet", "sheep", "weep", "week", "peek", "peel"],
  ["sheet", "sheep", "weep", "week", "peek", "cheek"],
  ["steam", "steal", "steel", "steep", "sweep", "sweet"],
  ["sweet", "sweep", "steep", "steel", "steal", "steam"],
  ["tea", "pea", "sea", "see", "fee", "bee"],
  ["tea", "pea", "sea", "see", "bee", "fee"],
  ["week", "weep", "sheep", "sheet", "meet", "meat"],
  ["week", "weep", "sheep", "sheet", "meet", "beet"],
  ["week", "weep", "sheep", "sheet", "beet", "meet"],
  ["week", "weep", "sheep", "sheet", "beet", "beep"],
  ["week", "weep", "sheep", "sheet", "beet", "beat"],
  ["weep", "week", "seek", "peek", "peel", "wheel"],
  ["weep", "week", "seek", "peek", "peel", "feel"],
  ["weep", "week", "seek", "cheek", "peek", "peel"],
  ["weep", "week", "peek", "peel", "wheel", "feel"],
  ["weep", "week", "peek", "peel", "feel", "wheel"],
  ["wheel", "peel", "peek", "week", "weep", "sheep"],
  ["wheel", "peel", "peek", "week", "weep", "deep"],
  ["wheel", "peel", "peek", "week", "weep", "beep"],
  ["wheel", "peel", "peek", "week", "seek", "cheek"],
  ["wheel", "peel", "peek", "week", "cheek", "seek"],
];

// expose as globals for your HTML (non-module)
window.longE_words = longE_words;
window.longEWordLadders = longEWordLadders;
