// Auto-generated ladder data for Multisyllabic Word Ladders (pictured words only)
(function(){
  window.multisyllabicLadderData = {
  "title": "Multisyllabic Word Ladders",
  "subtitle": "Choose a multisyllabic set and generate a 6-step ladder.",
  "setOrder": [
    "closed",
    "open",
    "vce",
    "mixed"
  ],
  "setLabels": {
    "closed": "Multisyllabic (Closed)",
    "open": "Multisyllabic (Open)",
    "vce": "Multisyllabic (VCe)",
    "mixed": "Multisyllabic Mixed"
  },
  "wordPatterns": {
    "album": "23",
    "anchor": "23",
    "appendix": "233",
    "atlas": "23",
    "attic": "23",
    "backbone": "33",
    "backdrop": "33",
    "backpack": "33",
    "bagpipe": "33",
    "barcode": "33",
    "basement": "33",
    "basket": "33",
    "basketball": "333",
    "bathmat": "33",
    "bathtub": "33",
    "bedbug": "33",
    "bedrock": "33",
    "beehive": "33",
    "bible": "23",
    "bishop": "32",
    "blacksmith": "33",
    "blanket": "33",
    "bonfire": "33",
    "bracelet": "33",
    "bucket": "32",
    "bugle": "23",
    "button": "33",
    "cabinet": "313",
    "cable": "23",
    "cactus": "33",
    "cannon": "33",
    "canyon": "33",
    "capsule": "33",
    "cashbox": "33",
    "catfish": "33",
    "catnap": "33",
    "catnip": "33",
    "caveman": "33",
    "chapel": "32",
    "chestnut": "33",
    "chicken": "32",
    "chipmunk": "33",
    "chopstick": "33",
    "classmate": "33",
    "coastline": "33",
    "cobweb": "33",
    "costume": "33",
    "cotton": "33",
    "cradle": "33",
    "cricket": "32",
    "crocodile": "313",
    "curbside": "33",
    "cycle": "23",
    "dentist": "33",
    "desktop": "33",
    "dishcloth": "33",
    "dishpan": "33",
    "dishrag": "33",
    "dolphin": "33",
    "duckling": "33",
    "dustbin": "33",
    "eggplant": "33",
    "fabric": "33",
    "fireman": "33",
    "fishnet": "33",
    "flapjack": "33",
    "fossil": "33",
    "gallon": "33",
    "goblin": "33",
    "gopher": "23",
    "grapevine": "33",
    "gumdrop": "33",
    "handshake": "33",
    "helmet": "33",
    "homeplate": "33",
    "hotdog": "33",
    "hubcap": "33",
    "hurricane": "323",
    "infant": "23",
    "paper": "23"
  },
  "wordImages": {
    "album": "images/album.png",
    "anchor": "images/anchor.png",
    "appendix": "images/appendix.png",
    "atlas": "images/atlas.png",
    "attic": "images/attic.png",
    "backbone": "images/backbone.png",
    "backdrop": "images/backdrop.png",
    "backpack": "images/backpack.png",
    "bagpipe": "images/bagpipe.png",
    "barcode": "images/barcode.png",
    "basement": "images/basement.png",
    "basket": "images/basket.png",
    "basketball": "images/basketball.png",
    "bathmat": "images/bathmat.png",
    "bathtub": "images/bathtub.png",
    "bedbug": "images/bedbug.png",
    "bedrock": "images/bedrock.png",
    "beehive": "images/beehive.png",
    "bible": "images/bible.png",
    "bishop": "images/bishop.png",
    "blacksmith": "images/blacksmith.png",
    "blanket": "images/blanket.png",
    "bonfire": "images/bonfire.png",
    "bracelet": "images/bracelet.png",
    "bucket": "images/bucket.png",
    "bugle": "images/bugle.png",
    "button": "images/button.png",
    "cabinet": "images/cabinet.png",
    "cable": "images/cable.png",
    "cactus": "images/cactus.png",
    "cannon": "images/cannon.png",
    "canyon": "images/canyon.png",
    "capsule": "images/capsule.png",
    "cashbox": "images/cashbox.png",
    "catfish": "images/catfish.png",
    "catnap": "images/catnap.png",
    "catnip": "images/catnip.png",
    "caveman": "images/caveman.png",
    "chapel": "images/chapel.png",
    "chestnut": "images/chestnut.png",
    "chicken": "images/chicken.png",
    "chipmunk": "images/chipmunk.png",
    "chopstick": "images/chopstick.png",
    "classmate": "images/classmate.png",
    "coastline": "images/coastline.png",
    "cobweb": "images/cobweb.png",
    "costume": "images/costume.png",
    "cotton": "images/cotton.png",
    "cradle": "images/cradle.png",
    "cricket": "images/cricket.png",
    "crocodile": "images/crocodile.png",
    "curbside": "images/curbside.png",
    "cycle": "images/cycle.png",
    "dentist": "images/dentist.png",
    "desktop": "images/desktop.png",
    "dishcloth": "images/dishcloth.png",
    "dishpan": "images/dishpan.png",
    "dishrag": "images/dishrag.png",
    "dolphin": "images/dolphin.png",
    "duckling": "images/duckling.png",
    "dustbin": "images/dustbin.png",
    "eggplant": "images/eggplant.png",
    "fabric": "images/fabric.png",
    "fireman": "images/fireman.png",
    "fishnet": "images/fishnet.png",
    "flapjack": "images/flapjack.png",
    "fossil": "images/fossil.png",
    "gallon": "images/gallon.png",
    "goblin": "images/goblin.png",
    "gopher": "images/gopher.png",
    "grapevine": "images/grapevine.png",
    "gumdrop": "images/gumdrop.png",
    "handshake": "images/handshake.png",
    "helmet": "images/helmet.png",
    "homeplate": "images/homeplate.png",
    "hotdog": "images/hotdog.png",
    "hubcap": "images/hubcap.png",
    "hurricane": "images/hurricane.png",
    "infant": "images/infant.png",
    "paper": "images/paper.png"
  },
  "ladders": {
    "closed": [
      [
        "atlas",
        "attic",
        "atlas",
        "attic",
        "atlas",
        "attic"
      ],
      [
        "attic",
        "atlas",
        "attic",
        "atlas",
        "attic",
        "atlas"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basketball"
      ],
      [
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket"
      ],
      [
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub"
      ],
      [
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat"
      ],
      [
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock"
      ],
      [
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug"
      ],
      [
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket"
      ],
      [
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith"
      ],
      [
        "button",
        "cotton",
        "button",
        "cotton",
        "button",
        "cotton"
      ],
      [
        "cannon",
        "canyon",
        "cannon",
        "canyon",
        "cannon",
        "canyon"
      ],
      [
        "canyon",
        "cannon",
        "canyon",
        "cannon",
        "canyon",
        "cannon"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "cricket"
      ],
      [
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "cotton",
        "button",
        "cotton",
        "button",
        "cotton",
        "button"
      ],
      [
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ]
    ],
    "open": [
      [
        "bible",
        "cable",
        "bible",
        "cable",
        "bible",
        "cable"
      ],
      [
        "cable",
        "bible",
        "cable",
        "bible",
        "cable",
        "bible"
      ]
    ],
    "vce": [
      [
        "caveman",
        "fireman",
        "caveman",
        "fireman",
        "caveman",
        "fireman"
      ],
      [
        "fireman",
        "caveman",
        "fireman",
        "caveman",
        "fireman",
        "caveman"
      ]
    ],
    "mixed": [
      [
        "atlas",
        "attic",
        "atlas",
        "attic",
        "atlas",
        "attic"
      ],
      [
        "attic",
        "atlas",
        "attic",
        "atlas",
        "attic",
        "atlas"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backbone",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backbone",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backbone"
      ],
      [
        "backpack",
        "backdrop",
        "backbone",
        "backpack",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backbone"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backdrop",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backbone",
        "backpack",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backdrop"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backbone",
        "backpack"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backbone"
      ],
      [
        "backpack",
        "backdrop",
        "backpack",
        "backdrop",
        "backpack",
        "backdrop"
      ],
      [
        "basement",
        "basket",
        "basement",
        "basket",
        "basement",
        "basket"
      ],
      [
        "basement",
        "basket",
        "basement",
        "basket",
        "basketball",
        "basket"
      ],
      [
        "basement",
        "basket",
        "basketball",
        "basket",
        "basement",
        "basket"
      ],
      [
        "basement",
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket"
      ],
      [
        "basket",
        "basement",
        "basket",
        "basement",
        "basket",
        "basement"
      ],
      [
        "basket",
        "basement",
        "basket",
        "basement",
        "basket",
        "basketball"
      ],
      [
        "basket",
        "basement",
        "basket",
        "basketball",
        "basket",
        "basement"
      ],
      [
        "basket",
        "basement",
        "basket",
        "basketball",
        "basket",
        "basketball"
      ],
      [
        "basket",
        "basketball",
        "basket",
        "basement",
        "basket",
        "basement"
      ],
      [
        "basket",
        "basketball",
        "basket",
        "basement",
        "basket",
        "basketball"
      ],
      [
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basement"
      ],
      [
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basketball"
      ],
      [
        "basketball",
        "basket",
        "basement",
        "basket",
        "basement",
        "basket"
      ],
      [
        "basketball",
        "basket",
        "basement",
        "basket",
        "basketball",
        "basket"
      ],
      [
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basement",
        "basket"
      ],
      [
        "basketball",
        "basket",
        "basketball",
        "basket",
        "basketball",
        "basket"
      ],
      [
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub"
      ],
      [
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat",
        "bathtub",
        "bathmat"
      ],
      [
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock"
      ],
      [
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug",
        "bedrock",
        "bedbug"
      ],
      [
        "bible",
        "cable",
        "bible",
        "cable",
        "bible",
        "cable"
      ],
      [
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket"
      ],
      [
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith",
        "blanket",
        "blacksmith"
      ],
      [
        "button",
        "cotton",
        "button",
        "cotton",
        "button",
        "cotton"
      ],
      [
        "cable",
        "bible",
        "cable",
        "bible",
        "cable",
        "bible"
      ],
      [
        "cannon",
        "canyon",
        "cannon",
        "canyon",
        "cannon",
        "canyon"
      ],
      [
        "canyon",
        "cannon",
        "canyon",
        "cannon",
        "canyon",
        "cannon"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnap",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catfish",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catfish",
        "catnip",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnap",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catfish",
        "catnip",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnap"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catfish",
        "catnip"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catfish"
      ],
      [
        "catnip",
        "catnap",
        "catnip",
        "catnap",
        "catnip",
        "catnap"
      ],
      [
        "caveman",
        "fireman",
        "caveman",
        "fireman",
        "caveman",
        "fireman"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk"
      ],
      [
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "cricket"
      ],
      [
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "chipmunk",
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "cotton",
        "button",
        "cotton",
        "button",
        "cotton",
        "button"
      ],
      [
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "chipmunk",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "chipmunk",
        "chicken"
      ],
      [
        "cricket",
        "chicken",
        "cricket",
        "chicken",
        "cricket",
        "chicken"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishpan",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth",
        "dishrag",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishpan"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishcloth",
        "dishrag"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishcloth"
      ],
      [
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan",
        "dishrag",
        "dishpan"
      ],
      [
        "fireman",
        "caveman",
        "fireman",
        "caveman",
        "fireman",
        "caveman"
      ]
    ]
  },
  "counts": {
    "closed": {
      "words": 54,
      "ladders": 224
    },
    "open": {
      "words": 7,
      "ladders": 2
    },
    "vce": {
      "words": 19,
      "ladders": 2
    },
    "mixed": {
      "words": 80,
      "ladders": 336
    }
  }
};
})();
