soundBoxWords["Short A with Blends"] = [
soundBoxWords["Short O with Blends"] = [
soundBoxWords["Short I with Blends"] = [
soundBoxWords["Short U with Blends"] = [
soundBoxWords["Short E with Blends"] = [
soundBoxWords["VCe(a_e) with Blends"] = [
soundBoxWords["VCe(i_e) with Blends"] = [
soundBoxWords["VCe(o_e) with Blends"] = [
soundBoxWords["VCe(u_e) with Blends"] = [
soundBoxWords["Glued(all) with Blends"] = [
soundBoxWords["3.4 - ANK with Blends"] = [
soundBoxWords["Glued(ing) with Blends"] = [
soundBoxWords["Glued(ang) with Blends"] = [
soundBoxWords["Glued(onk) with Blends"] = [
soundBoxWords["Glued(unk) with Blends"] = [
soundBoxWords["Glued(ong) with Blends"] = [
soundBoxWords["Glued(ung) with Blends"] = [
soundBoxWords["R-Controlled(ar) with Blends"] = [
soundBoxWords["R-Controlled(or) with Blends"] = [
soundBoxWords["R-Controlled(er,ir,ur) with Blends"] = [
soundBoxWords["Long A(ay) with Blends"] = [
soundBoxWords["Long A(ai) with Blends"] = [
soundBoxWords["Long E(ee) with Blends"] = [
soundBoxWords["Long E(ea) with Blends"] = [
soundBoxWords["Long I(igh) with Blends"] = [
soundBoxWords["Long O(oa) with Blends"] = [
soundBoxWords["Long O(ow) with Blends"] = [
soundBoxWords["Long U(oo) with Blends"] = [
soundBoxWords["Long U(ew) with Blends "] = [
soundBoxWords["Diphthong(ou) with Blends"] = [
soundBoxWords["Diphthong(oi) with Blends"] = [
soundBoxWords["Diphthong(oy) with Blends"] = [
soundBoxWords["Variant Vowel(aw) with Blends"] = [
soundBoxWords["Variant Vowel(au) with Blends"] = [
soundBoxWords["Variant Vowel(oo) with Blends"] = [
soundBoxWords["Soft C (ce) with Blends"] = [