const vceWordLadders = [
  ["ate", "gate", "date", "late", "lake", "rake"],
  ["ate", "date", "late", "gate", "gave", "save"],
  ["ate", "date", "gate", "late", "lake", "bake"],
  ["ate", "date", "late", "gate", "game", "tame"],
  ["ate", "late", "date", "gate", "game", "gave"],
  ["ate", "late", "lake", "take", "cake", "cave"],
  ["bake", "lake", "rake", "fake", "take", "cake"],
  ["bake", "shake", "shape", "cape", "case", "chase"],
  ["bake", "make", "maze", "made", "fade", "shade"],
  ["bake", "fake", "lake", "rake", "take", "shake"],
  ["bake", "fake", "make", "maze", "made", "fade"],
  ["bake", "take", "rake", "make", "maze", "made"],
  ["bike", "bake", "lake", "rake", "shake", "cake"],
  ["bike", "bake", "fake", "shake", "shade", "fade"],
  ["bike", "hike", "hive", "hide", "ride", "rise"],
  ["bike", "bake", "shake", "shade", "shape", "tape"],
  ["bike", "bake", "rake", "shake", "take", "lake"],
  ["bike", "hike", "hide", "ride", "tide", "time"],
  ["bite", "bike", "hike", "hive", "five", "fine"],
  ["bite", "bike", "hike", "hide", "ride", "rode"],
  ["bite", "bike", "bake", "fake", "cake", "lake"],
  ["bite", "bike", "bake", "shake", "cake", "make"],
  ["bite", "bike", "hike", "hive", "dive", "dine"],
  ["bite", "bike", "bake", "fake", "shake", "cake"],
  ["bone", "cone", "code", "rode", "robe", "rope"],
  ["bone", "cone", "cove", "cave", "save", "sale"],
  ["bone", "lone", "line", "mine", "nine", "vine"],
  ["bone", "lone", "cone", "code", "rode", "rose"],
  ["bone", "lone", "line", "dine", "dune", "tune"],
  ["bone", "cone", "cove", "cave", "cape", "case"],
  ["cake", "cape", "case", "vase", "chase", "chose"],
  ["cake", "lake", "late", "gate", "gave", "save"],
  ["cake", "fake", "fade", "shade", "shape", "cape"],
  ["cake", "fake", "shake", "rake", "make", "lake"],
  ["cake", "case", "vase", "chase", "chose", "dose"],
  ["cake", "bake", "make", "maze", "made", "fade"],
  ["cape", "tape", "shape", "shade", "shake", "rake"],
  ["cape", "cake", "bake", "bike", "bite", "kite"],
  ["cape", "case", "cave", "save", "gave", "gate"],
  ["cape", "tape", "take", "lake", "fake", "shake"],
  ["cape", "cave", "case", "vase", "chase", "chose"],
  ["cape", "tape", "shape", "shade", "fade", "made"],
  ["case", "chase", "chose", "hose", "home", "dome"],
  ["case", "cake", "bake", "take", "tame", "time"],
  ["case", "vase", "chase", "chose", "hose", "pose"],
  ["case", "chase", "chose", "rose", "robe", "rode"],
  ["case", "cape", "shape", "shake", "cake", "make"],
  ["case", "chase", "chose", "hose", "dose", "rose"],
  ["cave", "save", "same", "game", "gave", "gate"],
  ["cave", "cake", "take", "shake", "make", "maze"],
  ["cave", "cape", "shape", "shade", "shake", "rake"],
  ["cave", "cake", "bake", "lake", "take", "shake"],
  ["cave", "case", "vase", "chase", "chose", "pose"],
  ["cave", "gave", "save", "sale", "pale", "whale"],
  ["chase", "chose", "rose", "robe", "rope", "rode"],
  ["chase", "vase", "case", "cake", "cape", "shape"],
  ["chase", "vase", "case", "cake", "make", "lake"],
  ["chase", "vase", "case", "cake", "cave", "cape"],
  ["chase", "case", "cave", "save", "sale", "whale"],
  ["chase", "chose", "rose", "pose", "poke", "joke"],
  ["chime", "dime", "dome", "dose", "hose", "rose"],
  ["chime", "dime", "dine", "fine", "file", "five"],
  ["chime", "lime", "time", "tide", "ride", "rude"],
  ["chime", "dime", "lime", "line", "vine", "mine"],
  ["chime", "lime", "line", "nine", "shine", "fine"],
  ["chime", "dime", "dive", "hive", "hide", "hike"],
  ["chose", "hose", "pose", "rose", "rise", "ride"],
  ["chose", "hose", "pose", "dose", "doze", "dome"],
  ["chose", "dose", "rose", "robe", "rode", "rude"],
  ["chose", "hose", "rose", "rope", "robe", "rode"],
  ["chose", "dose", "rose", "rise", "wise", "wife"],
  ["chose", "hose", "hole", "home", "dome", "dime"],
  ["code", "cove", "cave", "cape", "tape", "tame"],
  ["code", "cove", "cave", "cake", "case", "chase"],
  ["code", "cone", "bone", "lone", "line", "nine"],
  ["code", "cone", "cove", "cave", "case", "vase"],
  ["code", "cone", "lone", "line", "dine", "dune"],
  ["code", "cone", "cove", "cave", "gave", "save"],
  ["cone", "code", "cove", "cave", "case", "chase"],
  ["cone", "bone", "lone", "line", "dine", "dive"],
  ["cone", "code", "cove", "cave", "gave", "game"],
  ["cone", "cove", "cave", "save", "same", "tame"],
  ["cone", "lone", "line", "nine", "shine", "vine"],
  ["cone", "code", "rode", "ride", "rise", "rose"],
  ["cove", "cave", "case", "chase", "chose", "pose"],
  ["cove", "cave", "save", "sale", "same", "tame"],
  ["cove", "cave", "cape", "cake", "bake", "shake"],
  ["cove", "cone", "bone", "lone", "line", "shine"],
  ["cove", "cave", "cake", "cape", "tape", "shape"],
  ["cove", "code", "cone", "bone", "lone", "line"],
  ["cube", "tube", "tune", "dune", "dine", "nine"],
  ["cube", "tube", "tune", "june", "dune", "dine"],
  ["cube", "cute", "mute", "mule", "rule", "rude"],
  ["cute", "mute", "mule", "rule", "rude", "rode"],
  ["cute", "cube", "tube", "tune", "june", "dune"],
  ["date", "ate", "gate", "game", "gave", "save"],
  ["date", "ate", "late", "lake", "cake", "case"],
  ["date", "ate", "late", "gate", "gave", "cave"],
  ["date", "gate", "ate", "late", "lake", "rake"],
  ["date", "gate", "gave", "game", "same", "sale"],
  ["date", "late", "ate", "gate", "game", "gave"],
  ["dime", "time", "tame", "same", "save", "gave"],
  ["dime", "lime", "time", "tame", "take", "fake"],
  ["dime", "dive", "five", "file", "fine", "mine"],
  ["dime", "lime", "line", "fine", "five", "file"],
  ["dime", "dine", "nine", "vine", "shine", "fine"],
  ["dime", "dine", "dune", "june", "tune", "tube"],
  ["dine", "dive", "hive", "hike", "hide", "tide"],
  ["dine", "nine", "shine", "vine", "mine", "fine"],
  ["dine", "dime", "lime", "chime", "time", "tame"],
  ["dine", "line", "nine", "mine", "vine", "shine"],
  ["dine", "line", "lone", "cone", "cove", "code"],
  ["dine", "nine", "mine", "line", "lime", "chime"],
  ["dive", "dine", "vine", "line", "fine", "five"],
  ["dive", "dime", "dome", "home", "hole", "hose"],
  ["dive", "hive", "hike", "bike", "bite", "kite"],
  ["dive", "hive", "hike", "hide", "tide", "time"],
  ["dive", "dime", "lime", "line", "lone", "cone"],
  ["dive", "dine", "fine", "shine", "line", "nine"],
  ["dome", "dime", "dive", "dine", "mine", "line"],
  ["dome", "dose", "pose", "rose", "robe", "rode"],
  ["dome", "dose", "chose", "pose", "poke", "woke"],
  ["dome", "home", "hole", "hose", "dose", "rose"],
  ["dome", "dose", "chose", "chase", "case", "vase"],
  ["dome", "dime", "chime", "time", "tide", "hide"],
  ["dose", "chose", "pose", "poke", "woke", "joke"],
  ["dose", "rose", "rise", "ride", "hide", "hive"],
  ["dose", "pose", "chose", "rose", "rode", "rude"],
  ["dose", "chose", "chase", "case", "cave", "save"],
  ["dose", "doze", "dome", "home", "hose", "hole"],
  ["dose", "hose", "rose", "rise", "wise", "wife"],
  ["doze", "dose", "hose", "rose", "rise", "ride"],
  ["doze", "dose", "chose", "rose", "rise", "wise"],
  ["doze", "dome", "dime", "lime", "chime", "time"],
  ["doze", "dome", "dose", "rose", "chose", "hose"],
  ["doze", "dose", "pose", "poke", "joke", "woke"],
  ["doze", "dome", "dose", "chose", "chase", "vase"],
  ["dune", "june", "tune", "tube", "cube", "cute"],
  ["dune", "dine", "shine", "fine", "line", "mine"],
  ["dune", "tune", "tube", "cube", "cute", "mute"],
  ["dune", "dine", "fine", "vine", "line", "nine"],
  ["dune", "dine", "shine", "line", "lone", "cone"],
  ["dune", "dine", "dive", "five", "file", "fine"],
  ["fade", "made", "maze", "make", "take", "rake"],
  ["fade", "made", "maze", "make", "cake", "cave"],
  ["fade", "fame", "game", "gate", "gave", "save"],
  ["fade", "shade", "shape", "tape", "take", "make"],
  ["fade", "made", "shade", "shake", "shape", "cape"],
  ["fade", "made", "shade", "shape", "tape", "tame"],
  ["fake", "bake", "shake", "cake", "rake", "make"],
  ["fake", "take", "tame", "fame", "same", "sale"],
  ["fake", "take", "tape", "shape", "shake", "bake"],
  ["fake", "take", "lake", "late", "date", "gate"],
  ["fake", "fade", "shade", "shake", "shape", "cape"],
  ["fake", "cake", "cave", "cove", "code", "cone"],
  ["fame", "fake", "take", "shake", "bake", "bike"],
  ["fame", "tame", "take", "lake", "bake", "fake"],
  ["fame", "tame", "time", "tide", "ride", "rude"],
  ["fame", "same", "sale", "save", "gave", "cave"],
  ["fame", "same", "save", "gave", "game", "tame"],
  ["fame", "fade", "shade", "made", "make", "maze"],
  ["file", "five", "dive", "hive", "hide", "ride"],
  ["file", "fine", "line", "lime", "time", "tame"],
  ["file", "five", "fine", "vine", "shine", "mine"],
  ["file", "five", "dive", "dine", "fine", "vine"],
  ["file", "fine", "dine", "dime", "dive", "five"],
  ["file", "fine", "nine", "shine", "line", "lone"],
  ["fine", "line", "lone", "bone", "cone", "code"],
  ["fine", "file", "five", "hive", "dive", "dime"],
  ["fine", "shine", "vine", "nine", "dine", "dive"],
  ["fine", "file", "five", "hive", "hide", "hike"],
  ["fine", "mine", "nine", "vine", "shine", "line"],
  ["fine", "shine", "mine", "dine", "vine", "nine"],
  ["five", "dive", "dine", "mine", "vine", "shine"],
  ["five", "dive", "dime", "time", "chime", "lime"],
  ["five", "fine", "vine", "dine", "nine", "line"],
  ["five", "file", "fine", "vine", "dine", "dune"],
  ["five", "file", "fine", "mine", "nine", "dine"],
  ["five", "file", "fine", "mine", "vine", "nine"],
  ["fume", "fame", "same", "tame", "tape", "shape"],
  ["fume", "fame", "tame", "game", "gave", "gate"],
  ["fume", "fame", "same", "save", "gave", "cave"],
  ["fume", "fame", "fade", "shade", "shake", "lake"],
  ["fume", "fame", "fade", "fake", "bake", "make"],
  ["fume", "fame", "game", "gave", "save", "same"],
  ["game", "same", "sale", "save", "cave", "case"],
  ["game", "gate", "gave", "cave", "save", "same"],
  ["game", "fame", "fake", "lake", "bake", "make"],
  ["game", "fame", "tame", "time", "chime", "lime"],
  ["game", "gave", "save", "sale", "pale", "whale"],
  ["game", "fame", "fake", "fade", "shade", "shake"],
  ["gate", "game", "fame", "tame", "tape", "take"],
  ["gate", "date", "ate", "late", "lake", "shake"],
  ["gate", "late", "lake", "cake", "rake", "fake"],
  ["gate", "ate", "late", "lake", "cake", "bake"],
  ["gate", "gave", "save", "cave", "cake", "case"],
  ["gate", "late", "lake", "rake", "cake", "make"],
  ["gave", "save", "cave", "cake", "make", "lake"],
  ["gave", "game", "gate", "ate", "late", "date"],
  ["gave", "gate", "game", "same", "tame", "take"],
  ["gave", "cave", "cape", "tape", "shape", "shake"],
  ["gave", "game", "fame", "fade", "made", "maze"],
  ["gave", "cave", "cove", "cone", "bone", "lone"],
  ["hide", "hike", "bike", "bake", "rake", "take"],
  ["hide", "ride", "rode", "rope", "rose", "chose"],
  ["hide", "hike", "bike", "bake", "make", "cake"],
  ["hide", "tide", "ride", "rise", "wise", "wife"],
  ["hide", "ride", "tide", "time", "dime", "dive"],
  ["hide", "hike", "hive", "five", "fine", "vine"],
  ["hike", "hive", "hide", "tide", "time", "chime"],
  ["hike", "hive", "hide", "tide", "ride", "rise"],
  ["hike", "hive", "five", "fine", "line", "shine"],
  ["hike", "bike", "bake", "cake", "fake", "shake"],
  ["hike", "hive", "dive", "dime", "time", "tame"],
  ["hike", "hide", "hive", "five", "file", "fine"],
  ["hive", "hike", "hide", "ride", "rode", "rose"],
  ["hive", "hike", "hide", "ride", "tide", "time"],
  ["hive", "hide", "hike", "bike", "bake", "fake"],
  ["hive", "five", "fine", "mine", "vine", "line"],
  ["hive", "hide", "ride", "rode", "rope", "robe"],
  ["hive", "hide", "tide", "ride", "rise", "wise"],
  ["hole", "hose", "pose", "poke", "woke", "joke"],
  ["hole", "home", "hose", "dose", "doze", "dome"],
  ["hole", "home", "hose", "pose", "rose", "dose"],
  ["hole", "home", "hose", "chose", "pose", "poke"],
  ["hole", "hose", "rose", "rise", "ride", "rode"],
  ["hole", "hose", "home", "dome", "dime", "dive"],
  ["home", "hose", "rose", "rise", "ride", "tide"],
  ["home", "hose", "rose", "dose", "chose", "chase"],
  ["home", "dome", "dose", "pose", "hose", "chose"],
  ["home", "hole", "hose", "pose", "poke", "joke"],
  ["home", "hose", "pose", "rose", "rode", "rude"],
  ["home", "hole", "hose", "dose", "rose", "rode"],
  ["hose", "pose", "rose", "rode", "rope", "robe"],
  ["hose", "rose", "chose", "chase", "case", "cape"],
  ["hose", "rose", "rode", "ride", "hide", "hive"],
  ["hose", "chose", "dose", "rose", "rope", "rode"],
  ["hose", "home", "dome", "doze", "dose", "chose"],
  ["hose", "dose", "doze", "dome", "home", "hole"],
  ["joke", "woke", "poke", "pose", "rose", "robe"],
  ["joke", "poke", "pose", "dose", "dome", "home"],
  ["joke", "woke", "poke", "pose", "dose", "hose"],
  ["joke", "woke", "poke", "pose", "chose", "dose"],
  ["joke", "poke", "pose", "rose", "rode", "ride"],
  ["joke", "poke", "pose", "chose", "rose", "rope"],
  ["june", "dune", "tune", "tube", "cube", "cute"],
  ["june", "tune", "dune", "dine", "line", "nine"],
  ["june", "tune", "tube", "cube", "cute", "mute"],
  ["june", "tune", "dune", "dine", "dive", "hive"],
  ["june", "dune", "dine", "shine", "fine", "vine"],
  ["june", "tune", "dune", "dine", "shine", "line"],
  ["kite", "bite", "bike", "hike", "hide", "hive"],
  ["kite", "bite", "bike", "bake", "rake", "shake"],
  ["kite", "bite", "bike", "bake", "make", "take"],
  ["kite", "bite", "bike", "bake", "lake", "make"],
  ["kite", "bite", "bike", "bake", "cake", "lake"],
  ["kite", "bite", "bike", "bake", "fake", "rake"],
  ["lake", "make", "take", "cake", "cape", "tape"],
  ["lake", "shake", "rake", "bake", "make", "fake"],
  ["lake", "shake", "take", "make", "bake", "cake"],
  ["lake", "late", "ate", "date", "gate", "gave"],
  ["lake", "rake", "make", "bake", "shake", "shape"],
  ["lake", "shake", "rake", "take", "tame", "time"],
  ["late", "ate", "date", "gate", "gave", "game"],
  ["late", "date", "ate", "gate", "gave", "save"],
  ["late", "date", "gate", "gave", "cave", "cove"],
  ["late", "lake", "cake", "make", "rake", "fake"],
  ["late", "lake", "take", "shake", "bake", "bike"],
  ["late", "gate", "gave", "cave", "cape", "case"],
  ["lime", "dime", "dome", "doze", "dose", "rose"],
  ["lime", "time", "tide", "hide", "hive", "hike"],
  ["lime", "chime", "time", "tide", "ride", "rode"],
  ["lime", "line", "vine", "mine", "nine", "shine"],
  ["lime", "time", "chime", "dime", "dome", "dose"],
  ["lime", "time", "tame", "take", "make", "made"],
  ["line", "nine", "fine", "five", "hive", "hide"],
  ["line", "lone", "bone", "cone", "cove", "cave"],
  ["line", "shine", "mine", "nine", "dine", "vine"],
  ["line", "shine", "nine", "fine", "five", "hive"],
  ["line", "nine", "mine", "fine", "shine", "dine"],
  ["line", "nine", "fine", "file", "five", "dive"],
  ["lone", "bone", "cone", "code", "cove", "cave"],
  ["lone", "line", "shine", "dine", "dune", "june"],
  ["lone", "bone", "cone", "code", "rode", "rude"],
  ["lone", "cone", "code", "rode", "ride", "tide"],
  ["lone", "bone", "cone", "cove", "code", "rode"],
  ["lone", "cone", "cove", "code", "rode", "robe"],
  ["made", "shade", "shape", "tape", "tame", "fame"],
  ["made", "shade", "shake", "make", "cake", "take"],
  ["made", "shade", "shape", "cape", "cake", "make"],
  ["made", "maze", "make", "shake", "cake", "rake"],
  ["made", "maze", "make", "lake", "cake", "shake"],
  ["made", "shade", "fade", "fake", "cake", "cave"],
  ["make", "bake", "bike", "hike", "hide", "tide"],
  ["make", "cake", "shake", "fake", "rake", "lake"],
  ["make", "made", "fade", "fake", "bake", "bike"],
  ["make", "fake", "shake", "take", "tame", "time"],
  ["make", "bake", "fake", "fame", "tame", "tape"],
  ["make", "made", "shade", "shape", "shake", "fake"],
  ["maze", "make", "take", "fake", "bake", "cake"],
  ["maze", "made", "make", "fake", "fame", "fume"],
  ["maze", "made", "fade", "shade", "shape", "tape"],
  ["maze", "made", "make", "take", "shake", "shape"],
  ["maze", "made", "shade", "shake", "bake", "make"],
  ["maze", "made", "fade", "shade", "shake", "lake"],
  ["mine", "vine", "dine", "line", "lime", "dime"],
  ["mine", "dine", "nine", "vine", "shine", "fine"],
  ["mine", "line", "lone", "bone", "cone", "code"],
  ["mine", "line", "vine", "shine", "dine", "dive"],
  ["mine", "nine", "shine", "vine", "line", "lone"],
  ["mine", "shine", "dine", "line", "nine", "vine"],
  ["mule", "mute", "cute", "cube", "tube", "tune"],
  ["mule", "rule", "rude", "rode", "code", "cone"],
  ["mule", "rule", "rude", "rode", "robe", "rose"],
  ["mule", "rule", "rude", "rode", "rope", "robe"],
  ["mule", "rule", "rude", "rode", "ride", "rise"],
  ["mule", "rule", "rude", "ride", "rode", "rope"],
  ["mute", "mule", "rule", "rude", "ride", "rise"],
  ["mute", "cute", "cube", "tube", "tune", "june"],
  ["mute", "mule", "rule", "rude", "rode", "code"],
  ["nine", "vine", "mine", "dine", "fine", "five"],
  ["nine", "vine", "shine", "mine", "dine", "line"],
  ["nine", "mine", "fine", "file", "five", "hive"],
  ["nine", "mine", "shine", "dine", "vine", "fine"],
  ["nine", "mine", "vine", "shine", "dine", "dune"],
  ["nine", "dine", "dime", "chime", "lime", "time"],
  ["pale", "whale", "sale", "save", "gave", "gate"],
  ["pale", "sale", "save", "same", "tame", "game"],
  ["pale", "whale", "sale", "save", "same", "tame"],
  ["pale", "sale", "same", "save", "gave", "cave"],
  ["pale", "whale", "sale", "same", "fame", "fake"],
  ["pale", "sale", "save", "gave", "cave", "cape"],
  ["poke", "pose", "hose", "rose", "rise", "wise"],
  ["poke", "pose", "dose", "hose", "hole", "home"],
  ["poke", "pose", "rose", "dose", "hose", "hole"],
  ["poke", "pose", "chose", "dose", "rose", "hose"],
  ["poke", "pose", "dose", "rose", "robe", "rope"],
  ["poke", "pose", "rose", "chose", "dose", "dome"],
  ["pose", "dose", "doze", "dome", "home", "hose"],
  ["pose", "rose", "robe", "rope", "rode", "code"],
  ["pose", "rose", "rise", "ride", "tide", "hide"],
  ["pose", "dose", "rose", "rise", "wise", "wife"],
  ["pose", "dose", "rose", "chose", "chase", "vase"],
  ["pose", "dose", "rose", "rise", "ride", "rode"],
  ["rake", "lake", "fake", "cake", "cave", "gave"],
  ["rake", "fake", "shake", "make", "lake", "late"],
  ["rake", "bake", "cake", "shake", "make", "fake"],
  ["rake", "shake", "take", "bake", "make", "lake"],
  ["rake", "shake", "cake", "cape", "tape", "tame"],
  ["rake", "bake", "cake", "take", "make", "made"],
  ["ride", "rude", "rode", "rose", "chose", "hose"],
  ["ride", "tide", "time", "chime", "dime", "dive"],
  ["ride", "tide", "hide", "hive", "five", "file"],
  ["ride", "rise", "rose", "rope", "rode", "robe"],
  ["ride", "rise", "rose", "dose", "pose", "chose"],
  ["ride", "rude", "rule", "mule", "mute", "cute"],
  ["rise", "rose", "rode", "rude", "ride", "hide"],
  ["rise", "ride", "rode", "rose", "dose", "doze"],
  ["rise", "ride", "tide", "time", "tame", "fame"],
  ["rise", "ride", "rode", "rose", "chose", "chase"],
  ["rise", "rose", "rope", "robe", "rode", "code"],
  ["rise", "rose", "chose", "pose", "hose", "home"],
  ["robe", "rode", "rude", "rule", "mule", "mute"],
  ["robe", "rose", "rode", "ride", "tide", "hide"],
  ["robe", "rode", "rose", "rise", "ride", "rude"],
  ["robe", "rode", "rope", "rose", "chose", "chase"],
  ["robe", "rose", "hose", "hole", "home", "dome"],
  ["robe", "rope", "rose", "hose", "dose", "pose"],
  ["rode", "rope", "rose", "rise", "ride", "tide"],
  ["rode", "rope", "rose", "hose", "chose", "chase"],
  ["rode", "ride", "rise", "rose", "pose", "chose"],
  ["rode", "robe", "rope", "rose", "pose", "dose"],
  ["rode", "robe", "rope", "rose", "hose", "pose"],
  ["rode", "robe", "rose", "hose", "home", "hole"],
  ["rope", "rode", "robe", "rose", "hose", "dose"],
  ["rope", "rode", "ride", "hide", "hive", "dive"],
  ["rope", "robe", "rose", "pose", "poke", "joke"],
  ["rope", "rose", "hose", "home", "dome", "dime"],
  ["rope", "robe", "rose", "rise", "ride", "tide"],
  ["rope", "robe", "rose", "hose", "pose", "poke"],
  ["rose", "rode", "code", "cove", "cave", "cape"],
  ["rose", "rope", "rode", "code", "cove", "cone"],
  ["rose", "hose", "chose", "dose", "dome", "home"],
  ["rose", "rode", "ride", "tide", "time", "tame"],
  ["rose", "rise", "ride", "tide", "time", "chime"],
  ["rose", "rope", "robe", "rode", "code", "cove"],
  ["rude", "rule", "mule", "mute", "cute", "cube"],
  ["rude", "rode", "rose", "dose", "dome", "home"],
  ["rude", "rode", "robe", "rope", "rose", "rise"],
  ["rude", "ride", "hide", "hive", "five", "file"],
  ["rude", "ride", "rode", "rope", "rose", "chose"],
  ["rude", "ride", "rode", "rose", "hose", "dose"],
  ["rule", "mule", "mute", "cute", "cube", "tube"],
  ["rule", "rude", "ride", "rise", "rose", "rope"],
  ["rule", "rude", "ride", "rise", "wise", "wife"],
  ["rule", "rude", "rode", "robe", "rose", "pose"],
  ["rule", "rude", "ride", "tide", "time", "chime"],
  ["rule", "rude", "rode", "rose", "chose", "hose"],
  ["sale", "save", "same", "game", "fame", "fume"],
  ["sale", "same", "fame", "game", "tame", "take"],
  ["sale", "same", "save", "cave", "cove", "cone"],
  ["sale", "save", "gave", "game", "tame", "fame"],
  ["sale", "same", "tame", "game", "gave", "save"],
  ["sale", "same", "tame", "time", "chime", "dime"],
  ["same", "tame", "take", "shake", "shade", "made"],
  ["same", "tame", "game", "gave", "cave", "save"],
  ["same", "fame", "fake", "bake", "make", "shake"],
  ["same", "fame", "game", "gate", "gave", "cave"],
  ["same", "fame", "game", "tame", "tape", "take"],
  ["same", "fame", "fake", "bake", "cake", "lake"],
  ["save", "cave", "cape", "case", "chase", "vase"],
  ["save", "cave", "cape", "shape", "shake", "make"],
  ["save", "cave", "case", "chase", "chose", "rose"],
  ["save", "cave", "case", "cape", "tape", "tame"],
  ["save", "same", "game", "gate", "ate", "late"],
  ["save", "gave", "game", "same", "fame", "fake"],
  ["shade", "shape", "tape", "cape", "cake", "make"],
  ["shade", "made", "fade", "fake", "rake", "take"],
  ["shade", "shake", "bake", "fake", "fade", "made"],
  ["shade", "shake", "cake", "case", "cape", "cave"],
  ["shade", "shape", "tape", "tame", "game", "gate"],
  ["shade", "shake", "bake", "lake", "late", "ate"],
  ["shake", "lake", "cake", "cape", "tape", "tame"],
  ["shake", "rake", "take", "fake", "fame", "fume"],
  ["shake", "shape", "tape", "take", "bake", "make"],
  ["shake", "take", "cake", "cave", "gave", "save"],
  ["shake", "rake", "lake", "cake", "case", "cave"],
  ["shake", "take", "lake", "fake", "fame", "game"],
  ["shape", "cape", "cave", "cove", "cone", "code"],
  ["shape", "shade", "made", "maze", "make", "bake"],
  ["shape", "shade", "made", "make", "fake", "fade"],
  ["shape", "shake", "lake", "fake", "rake", "make"],
  ["shape", "tape", "take", "lake", "cake", "shake"],
  ["shape", "cape", "cave", "gave", "gate", "game"],
  ["shine", "fine", "nine", "dine", "vine", "line"],
  ["shine", "nine", "vine", "dine", "dime", "dive"],
  ["shine", "vine", "nine", "dine", "dune", "june"],
  ["shine", "vine", "mine", "dine", "dune", "tune"],
  ["shine", "nine", "vine", "dine", "fine", "file"],
  ["shine", "nine", "fine", "five", "hive", "hike"],
  ["take", "cake", "shake", "shape", "tape", "tame"],
  ["take", "bake", "fake", "lake", "shake", "make"],
  ["take", "lake", "bake", "fake", "fame", "same"],
  ["take", "shake", "shade", "fade", "fake", "cake"],
  ["take", "bake", "fake", "fade", "made", "shade"],
  ["take", "tape", "shape", "shake", "bake", "bike"],
  ["tame", "tape", "take", "make", "fake", "cake"],
  ["tame", "time", "chime", "lime", "dime", "dive"],
  ["tame", "game", "gate", "date", "ate", "late"],
  ["tame", "time", "lime", "line", "nine", "dine"],
  ["tame", "same", "fame", "fake", "bake", "make"],
  ["tame", "take", "shake", "lake", "fake", "rake"],
  ["tape", "shape", "shake", "take", "cake", "case"],
  ["tape", "tame", "take", "cake", "make", "fake"],
  ["tape", "tame", "take", "make", "shake", "cake"],
  ["tape", "shape", "cape", "cave", "gave", "save"],
  ["tape", "shape", "cape", "cave", "cove", "cone"],
  ["tape", "shape", "shake", "bake", "rake", "lake"],
  ["tide", "hide", "hike", "hive", "five", "file"],
  ["tide", "ride", "rode", "rope", "rose", "dose"],
  ["tide", "time", "dime", "dine", "line", "lime"],
  ["tide", "time", "dime", "chime", "lime", "line"],
  ["tide", "hide", "ride", "rode", "rope", "rose"],
  ["tide", "time", "chime", "dime", "dive", "dine"],
  ["time", "lime", "line", "dine", "vine", "nine"],
  ["time", "chime", "lime", "line", "shine", "mine"],
  ["time", "lime", "line", "vine", "dine", "shine"],
  ["time", "tide", "hide", "ride", "rise", "rose"],
  ["time", "tide", "hide", "hive", "hike", "bike"],
  ["time", "tide", "hide", "ride", "rode", "rude"],
  ["tube", "tune", "june", "dune", "dine", "line"],
  ["tube", "cube", "cute", "mute", "mule", "rule"],
  ["tube", "tune", "dune", "dine", "dime", "dive"],
  ["tube", "tune", "dune", "dine", "fine", "shine"],
  ["tube", "tune", "dune", "dine", "mine", "fine"],
  ["tube", "tune", "dune", "dine", "vine", "mine"],
  ["tune", "dune", "dine", "shine", "vine", "nine"],
  ["tune", "tube", "cube", "cute", "mute", "mule"],
  ["tune", "june", "dune", "dine", "dime", "dive"],
  ["tune", "june", "dune", "dine", "vine", "mine"],
  ["tune", "dune", "dine", "line", "lone", "bone"],
  ["tune", "june", "dune", "dine", "line", "shine"],
  ["vase", "case", "cave", "cake", "make", "shake"],
  ["vase", "case", "cave", "cove", "code", "cone"],
  ["vase", "chase", "chose", "rose", "rode", "robe"],
  ["vase", "chase", "case", "cape", "shape", "shade"],
  ["vase", "case", "chase", "chose", "pose", "rose"],
  ["vase", "chase", "chose", "hose", "dose", "doze"],
  ["vine", "line", "dine", "dive", "hive", "hike"],
  ["vine", "dine", "dime", "chime", "time", "lime"],
  ["vine", "line", "shine", "dine", "dive", "dime"],
  ["vine", "nine", "fine", "dine", "shine", "line"],
  ["vine", "shine", "mine", "fine", "nine", "dine"],
  ["vine", "shine", "mine", "nine", "fine", "file"],
  ["whale", "pale", "sale", "same", "tame", "game"],
  ["whale", "pale", "sale", "save", "cave", "cape"],
  ["whale", "sale", "same", "save", "gave", "gate"],
  ["whale", "pale", "sale", "same", "fame", "tame"],
  ["whale", "pale", "sale", "same", "save", "gave"],
  ["whale", "sale", "save", "same", "fame", "fade"],
  ["wife", "wise", "rise", "ride", "rode", "robe"],
  ["wife", "wise", "rise", "ride", "rude", "rule"],
  ["wife", "wise", "rise", "rose", "rode", "code"],
  ["wife", "wise", "rise", "ride", "tide", "time"],
  ["wife", "wise", "rise", "rose", "pose", "hose"],
  ["wife", "wise", "rise", "ride", "hide", "tide"],
  ["wise", "rise", "rose", "robe", "rode", "code"],
  ["wise", "rise", "ride", "hide", "hive", "hike"],
  ["wise", "rise", "ride", "rode", "rope", "robe"],
  ["wise", "rise", "ride", "rude", "rode", "rose"],
  ["wise", "rise", "ride", "rode", "rude", "rule"],
  ["wise", "rise", "ride", "hide", "tide", "time"],
  ["woke", "poke", "pose", "hose", "rose", "robe"],
  ["woke", "joke", "poke", "pose", "chose", "hose"],
  ["woke", "joke", "poke", "pose", "rose", "dose"],
  ["woke", "poke", "pose", "chose", "chase", "vase"],
  ["woke", "poke", "pose", "rose", "rode", "rude"],
  ["woke", "poke", "pose", "chose", "rose", "rope"],
]

const vceWordPatterns = {
  "ate": "12",
  "bake": "112",
  "bike": "112",
  "bite": "112",
  "bone": "112",
  "cake": "112",
  "cape": "112",
  "case": "112",
  "cave": "112",
  "chase": "212",
  "chime": "212",
  "chose": "212",
  "code": "112",
  "cone": "112",
  "cove": "112",
  "cube": "112",
  "date": "112",
  "dime": "112",
  "dine": "112",
  "dive": "112",
  "dome": "112",
  "dose": "112",
  "doze": "112",
  "dune": "112",
  "fade": "112",
  "fake": "112",
  "fame": "112",
  "file": "112",
  "fine": "112",
  "five": "112",
  "fume": "112",
  "game": "112",
  "gate": "112",
  "gave": "112",
  "hide": "112",
  "hike": "112",
  "hive": "112",
  "hole": "112",
  "home": "112",
  "hose": "112",
  "joke": "112",
  "june": "112",
  "kite": "112",
  "lake": "112",
  "late": "112",
  "lime": "112",
  "line": "112",
  "lone": "112",
  "made": "112",
  "make": "112",
  "maze": "112",
  "mine": "112",
  "mule": "112",
  "mute": "112",
  "nine": "112",
  "note": "112",
  "pale": "112",
  "pipe": "112",
  "poke": "112",
  "pose": "112",
  "rake": "112",
  "ride": "112",
  "rise": "112",
  "robe": "112",
  "rode": "112",
  "rope": "112",
  "rose": "112",
  "rude": "112",
  "rule": "112",
  "sale": "112",
  "same": "112",
  "save": "112",
  "shade": "212",
  "shake": "212",
  "shape": "212",
  "shine": "212",
  "take": "112",
  "tame": "112",
  "tape": "112",
  "tide": "112",
  "time": "112",
  "tune": "112",
  "vase": "112",
  "vine": "112",
  "vote": "112",
  "whale": "212",
  "wife": "112",
  "wise": "112",
  "tube": "112",
  "cute": "112",
  "woke": "112"
};

const vceWordImages = {
  "ate": "images/ate.png",
  "bake": "images/bake.png",
  "bike": "images/bike.png",
  "bite": "images/bite.png",
  "bone": "images/bone.png",
  "cake": "images/cake.png",
  "cape": "images/cape3.png",
  "case": "images/case.png",
  "cave": "images/cave.png",
  "chase": "images/chase.png",
  "chime": "images/chime.png",
  "chose": "images/chose.png",
  "code": "images/code.png",
  "cone": "images/cone.png",
  "cove": "images/cove.png",
  "cube": "images/cube.png",
  "cute": "images/cute.png",
  "date": "images/date.png",
  "dime": "images/dime.png",
  "dine": "images/dine.png",
  "dive": "images/dive.png",
  "dome": "images/dome.png",
  "dose": "images/dose.png",
  "doze": "images/doze.png",
  "dune": "images/dune.png",
  "fade": "images/fade.png",
  "fake": "images/fake.png",
  "fame": "images/fame.png",
  "file": "images/file.png",
  "fine": "images/fine.png",
  "five": "images/five.png",
  "fume": "images/fume.png",
  "game": "images/game.png",
  "gate": "images/gate.png",
  "gave": "images/gave.png",
  "hide": "images/hide.png",
  "hike": "images/hike.png",
  "hive": "images/hive.png",
  "hole": "images/hole.png",
  "home": "images/home.png",
  "hose": "images/hose.png",
  "joke": "images/joke.png",
  "june": "images/june.png",
  "kite": "images/kite.png",
  "lake": "images/lake.png",
  "late": "images/late.png",
  "lime": "images/lime.png",
  "line": "images/line.png",
  "lone": "images/lone.png",
  "made": "images/made.png",
  "make": "images/make.png",
  "maze": "images/maze.png",
  "mine": "images/mine.png",
  "mule": "images/mule.png",
  "mute": "images/mute.png",
  "nine": "images/nine.png",
  "note": "images/note.png",
  "pale": "images/pale.png",
  "pipe": "images/pipe.png",
  "poke": "images/poke.png",
  "pose": "images/pose.png",
  "rake": "images/rake.png",
  "ride": "images/ride.png",
  "rise": "images/rise.png",
  "robe": "images/robe.png",
  "rode": "images/rode.png",
  "rope": "images/rope.png",
  "rose": "images/rose.png",
  "rude": "images/rude.png",
  "rule": "images/rule.png",
  "sale": "images/sale.png",
  "same": "images/same.png",
  "save": "images/save.png",
  "shade": "images/shade.png",
  "shake": "images/shake.png",
  "shape": "images/shape.png",
  "shine": "images/shine.png",
  "take": "images/take.png",
  "tame": "images/tame.png",
  "tape": "images/tape.png",
  "tide": "images/tide.png",
  "time": "images/time.png",
  "tube": "images/tube.png",
  "tune": "images/tune.png",
  "vase": "images/vase.png",
  "vine": "images/vine.png",
  "vote": "images/vote.png",
  "whale": "images/whale.png",
  "wife": "images/wife.png",
  "wise": "images/wise.png",
  "woke": "images/woke.png"
};
