var digraphWordLadders = [
  ["back", "tack", "tuck", "tick", "sick", "suck"],
  ["back", "tack", "tuck", "tick", "sick", "sock"],
  ["back", "tack", "tuck", "tick", "sick", "sack"],
  ["back", "tack", "tuck", "tick", "sick", "pick"],
  ["back", "tack", "tuck", "tick", "sick", "lick"],
  ["back", "tack", "tuck", "tick", "sick", "kick"],
  ["bash", "rash", "mash", "math", "path", "bath"],
  ["bash", "rash", "mash", "math", "bath", "path"],
  ["bash", "rash", "mash", "lash", "gash", "dash"],
  ["bash", "rash", "mash", "lash", "gash", "cash"],
  ["bash", "rash", "mash", "lash", "dash", "gash"],
  ["bash", "rash", "mash", "lash", "dash", "dish"],
  ["bath", "path", "math", "mash", "rash", "rush"],
  ["bath", "path", "math", "mash", "rash", "lash"],
  ["bath", "path", "math", "mash", "rash", "gash"],
  ["bath", "path", "math", "mash", "rash", "dash"],
  ["bath", "path", "math", "mash", "rash", "cash"],
  ["bath", "path", "math", "mash", "rash", "bash"],
  ["buck", "tuck", "tick", "tack", "sack", "suck"],
  ["buck", "tuck", "tick", "tack", "sack", "sock"],
  ["buck", "tuck", "tick", "tack", "sack", "sick"],
  ["buck", "tuck", "tick", "tack", "sack", "rack"],
  ["buck", "tuck", "tick", "tack", "sack", "pack"],
  ["buck", "tuck", "tick", "tack", "sack", "back"],
  ["cash", "rash", "mash", "math", "path", "bath"],
  ["cash", "rash", "mash", "math", "bath", "path"],
  ["cash", "rash", "mash", "math", "bath", "bash"],
  ["cash", "rash", "mash", "lash", "gash", "dash"],
  ["cash", "rash", "mash", "lash", "gash", "bash"],
  ["cash", "rash", "mash", "lash", "dash", "gash"],
  ["chin", "chip", "chop", "shop", "shot", "shut"],
  ["dash", "rash", "mash", "math", "path", "bath"],
  ["dash", "rash", "mash", "math", "bath", "path"],
  ["dash", "rash", "mash", "math", "bath", "bash"],
  ["dash", "rash", "mash", "lash", "gash", "cash"],
  ["dash", "rash", "mash", "lash", "gash", "bash"],
  ["dash", "rash", "mash", "lash", "cash", "gash"],
  ["deck", "peck", "puck", "tuck", "tick", "tack"],
  ["deck", "peck", "puck", "tuck", "tick", "sick"],
  ["deck", "peck", "puck", "tuck", "tick", "pick"],
  ["deck", "peck", "puck", "tuck", "tick", "lick"],
  ["deck", "peck", "puck", "tuck", "tick", "kick"],
  ["deck", "peck", "puck", "tuck", "tack", "tick"],
  ["dish", "dash", "rash", "mash", "math", "path"],
  ["dish", "dash", "rash", "mash", "math", "moth"],
  ["dish", "dash", "rash", "mash", "math", "bath"],
  ["dish", "dash", "rash", "mash", "lash", "gash"],
  ["dish", "dash", "rash", "mash", "lash", "cash"],
  ["dish", "dash", "rash", "mash", "lash", "bash"],
  ["dock", "sock", "suck", "tuck", "tick", "tack"],
  ["dock", "sock", "suck", "tuck", "tick", "sick"],
  ["dock", "sock", "suck", "tuck", "tick", "pick"],
  ["dock", "sock", "suck", "tuck", "tick", "lick"],
  ["dock", "sock", "suck", "tuck", "tick", "kick"],
  ["dock", "sock", "suck", "tuck", "tack", "tick"],
  ["duck", "tuck", "tick", "tack", "sack", "suck"],
  ["duck", "tuck", "tick", "tack", "sack", "sock"],
  ["duck", "tuck", "tick", "tack", "sack", "sick"],
  ["duck", "tuck", "tick", "tack", "sack", "rack"],
  ["duck", "tuck", "tick", "tack", "sack", "pack"],
  ["duck", "tuck", "tick", "tack", "sack", "back"],
  ["fish", "wish", "dish", "dash", "rash", "rush"],
  ["fish", "wish", "dish", "dash", "rash", "mash"],
  ["fish", "wish", "dish", "dash", "rash", "lash"],
  ["fish", "wish", "dish", "dash", "rash", "gash"],
  ["fish", "wish", "dish", "dash", "rash", "cash"],
  ["fish", "wish", "dish", "dash", "rash", "bash"],
  ["gash", "rash", "mash", "math", "path", "bath"],
  ["gash", "rash", "mash", "math", "bath", "path"],
  ["gash", "rash", "mash", "math", "bath", "bash"],
  ["gash", "rash", "mash", "lash", "dash", "dish"],
  ["gash", "rash", "mash", "lash", "dash", "cash"],
  ["gash", "rash", "mash", "lash", "dash", "bash"],
  ["hush", "rush", "rash", "mash", "math", "path"],
  ["hush", "rush", "rash", "mash", "math", "moth"],
  ["hush", "rush", "rash", "mash", "math", "bath"],
  ["hush", "rush", "rash", "mash", "lash", "gash"],
  ["hush", "rush", "rash", "mash", "lash", "dash"],
  ["hush", "rush", "rash", "mash", "lash", "cash"],
  ["kick", "tick", "tuck", "tack", "sack", "suck"],
  ["kick", "tick", "tuck", "tack", "sack", "sock"],
  ["kick", "tick", "tuck", "tack", "sack", "sick"],
  ["kick", "tick", "tuck", "tack", "sack", "rack"],
  ["kick", "tick", "tuck", "tack", "sack", "pack"],
  ["kick", "tick", "tuck", "tack", "sack", "back"],
  ["lash", "rash", "mash", "math", "path", "bath"],
  ["lash", "rash", "mash", "math", "bath", "path"],
  ["lash", "rash", "mash", "math", "bath", "bash"],
  ["lash", "rash", "mash", "gash", "dash", "dish"],
  ["lash", "rash", "mash", "gash", "dash", "cash"],
  ["lash", "rash", "mash", "gash", "dash", "bash"],
  ["lick", "tick", "tuck", "tack", "sack", "suck"],
  ["lick", "tick", "tuck", "tack", "sack", "sock"],
  ["lick", "tick", "tuck", "tack", "sack", "sick"],
  ["lick", "tick", "tuck", "tack", "sack", "rack"],
  ["lick", "tick", "tuck", "tack", "sack", "pack"],
  ["lick", "tick", "tuck", "tack", "sack", "back"],
  ["lock", "sock", "suck", "tuck", "tick", "tack"],
  ["lock", "sock", "suck", "tuck", "tick", "sick"],
  ["lock", "sock", "suck", "tuck", "tick", "pick"],
  ["lock", "sock", "suck", "tuck", "tick", "lick"],
  ["lock", "sock", "suck", "tuck", "tick", "kick"],
  ["lock", "sock", "suck", "tuck", "tack", "tick"],
  ["luck", "tuck", "tick", "tack", "sack", "suck"],
  ["luck", "tuck", "tick", "tack", "sack", "sock"],
  ["luck", "tuck", "tick", "tack", "sack", "sick"],
  ["luck", "tuck", "tick", "tack", "sack", "rack"],
  ["luck", "tuck", "tick", "tack", "sack", "pack"],
  ["luck", "tuck", "tick", "tack", "sack", "back"],
  ["mash", "rash", "lash", "gash", "dash", "dish"],
  ["mash", "rash", "lash", "gash", "dash", "cash"],
  ["mash", "rash", "lash", "gash", "dash", "bash"],
  ["mash", "rash", "lash", "gash", "cash", "dash"],
  ["mash", "rash", "lash", "gash", "cash", "bash"],
  ["mash", "rash", "lash", "gash", "bash", "dash"],
  ["math", "path", "bath", "bash", "rash", "rush"],
  ["math", "path", "bath", "bash", "rash", "mash"],
  ["math", "path", "bath", "bash", "rash", "lash"],
  ["math", "path", "bath", "bash", "rash", "gash"],
  ["math", "path", "bath", "bash", "rash", "dash"],
  ["math", "path", "bath", "bash", "rash", "cash"],
  ["moth", "math", "path", "bath", "bash", "rash"],
  ["moth", "math", "path", "bath", "bash", "mash"],
  ["moth", "math", "path", "bath", "bash", "lash"],
  ["moth", "math", "path", "bath", "bash", "gash"],
  ["moth", "math", "path", "bath", "bash", "dash"],
  ["moth", "math", "path", "bath", "bash", "cash"],
  ["neck", "peck", "puck", "tuck", "tick", "tack"],
  ["neck", "peck", "puck", "tuck", "tick", "sick"],
  ["neck", "peck", "puck", "tuck", "tick", "pick"],
  ["neck", "peck", "puck", "tuck", "tick", "lick"],
  ["neck", "peck", "puck", "tuck", "tick", "kick"],
  ["neck", "peck", "puck", "tuck", "tack", "tick"],
  ["pack", "tack", "tuck", "tick", "sick", "suck"],
  ["pack", "tack", "tuck", "tick", "sick", "sock"],
  ["pack", "tack", "tuck", "tick", "sick", "sack"],
  ["pack", "tack", "tuck", "tick", "sick", "pick"],
  ["pack", "tack", "tuck", "tick", "sick", "lick"],
  ["pack", "tack", "tuck", "tick", "sick", "kick"],
  ["path", "math", "mash", "rash", "rush", "hush"],
  ["path", "math", "mash", "rash", "lash", "gash"],
  ["path", "math", "mash", "rash", "lash", "dash"],
  ["path", "math", "mash", "rash", "lash", "cash"],
  ["path", "math", "mash", "rash", "lash", "bash"],
  ["path", "math", "mash", "rash", "gash", "lash"],
  ["peck", "puck", "tuck", "tick", "tack", "sack"],
  ["peck", "puck", "tuck", "tick", "tack", "rack"],
  ["peck", "puck", "tuck", "tick", "tack", "pack"],
  ["peck", "puck", "tuck", "tick", "tack", "back"],
  ["peck", "puck", "tuck", "tick", "sick", "suck"],
  ["peck", "puck", "tuck", "tick", "sick", "sock"],
  ["pick", "tick", "tuck", "tack", "sack", "suck"],
  ["pick", "tick", "tuck", "tack", "sack", "sock"],
  ["pick", "tick", "tuck", "tack", "sack", "sick"],
  ["pick", "tick", "tuck", "tack", "sack", "rack"],
  ["pick", "tick", "tuck", "tack", "sack", "pack"],
  ["pick", "tick", "tuck", "tack", "sack", "back"],
  ["puck", "tuck", "tick", "tack", "sack", "suck"],
  ["puck", "tuck", "tick", "tack", "sack", "sock"],
  ["puck", "tuck", "tick", "tack", "sack", "sick"],
  ["puck", "tuck", "tick", "tack", "sack", "rack"],
  ["puck", "tuck", "tick", "tack", "sack", "pack"],
  ["puck", "tuck", "tick", "tack", "sack", "back"],
  ["rack", "tack", "tuck", "tick", "sick", "suck"],
  ["rack", "tack", "tuck", "tick", "sick", "sock"],
  ["rack", "tack", "tuck", "tick", "sick", "sack"],
  ["rack", "tack", "tuck", "tick", "sick", "pick"],
  ["rack", "tack", "tuck", "tick", "sick", "lick"],
  ["rack", "tack", "tuck", "tick", "sick", "kick"],
  ["rash", "mash", "math", "path", "bath", "bash"],
  ["rash", "mash", "math", "bath", "bash", "lash"],
  ["rash", "mash", "math", "bath", "bash", "gash"],
  ["rash", "mash", "math", "bath", "bash", "dash"],
  ["rash", "mash", "math", "bath", "bash", "cash"],
  ["rash", "mash", "lash", "gash", "dash", "dish"],
  ["rock", "sock", "suck", "tuck", "tick", "tack"],
  ["rock", "sock", "suck", "tuck", "tick", "sick"],
  ["rock", "sock", "suck", "tuck", "tick", "pick"],
  ["rock", "sock", "suck", "tuck", "tick", "lick"],
  ["rock", "sock", "suck", "tuck", "tick", "kick"],
  ["rock", "sock", "suck", "tuck", "tack", "tick"],
  ["rush", "rash", "mash", "math", "path", "bath"],
  ["rush", "rash", "mash", "math", "bath", "path"],
  ["rush", "rash", "mash", "math", "bath", "bash"],
  ["rush", "rash", "mash", "lash", "gash", "dash"],
  ["rush", "rash", "mash", "lash", "gash", "cash"],
  ["rush", "rash", "mash", "lash", "gash", "bash"],
  ["sack", "tack", "tuck", "tick", "sick", "suck"],
  ["sack", "tack", "tuck", "tick", "sick", "sock"],
  ["sack", "tack", "tuck", "tick", "sick", "pick"],
  ["sack", "tack", "tuck", "tick", "sick", "lick"],
  ["sack", "tack", "tuck", "tick", "sick", "kick"],
  ["sack", "tack", "tuck", "tick", "pick", "sick"],
  ["shin", "thin", "chin", "chip", "whip", "whiz"],
  ["shin", "thin", "chin", "chip", "chop", "shop"],
  ["shin", "chin", "chip", "chop", "shop", "shot"],
  ["shop", "chop", "chip", "chin", "thin", "shin"],
  ["shop", "chop", "chip", "chin", "shin", "thin"],
  ["shot", "shop", "chop", "chip", "whip", "whiz"],
  ["shot", "shop", "chop", "chip", "chin", "thin"],
  ["shot", "shop", "chop", "chip", "chin", "shin"],
  ["shut", "shot", "shop", "chop", "chip", "whip"],
  ["shut", "shot", "shop", "chop", "chip", "chin"],
  ["sick", "tick", "tuck", "tack", "sack", "suck"],
  ["sick", "tick", "tuck", "tack", "sack", "sock"],
  ["sick", "tick", "tuck", "tack", "sack", "rack"],
  ["sick", "tick", "tuck", "tack", "sack", "pack"],
  ["sick", "tick", "tuck", "tack", "sack", "back"],
  ["sick", "tick", "tuck", "tack", "rack", "sack"],
  ["sock", "suck", "tuck", "tick", "tack", "sack"],
  ["sock", "suck", "tuck", "tick", "tack", "rack"],
  ["sock", "suck", "tuck", "tick", "tack", "pack"],
  ["sock", "suck", "tuck", "tick", "tack", "back"],
  ["sock", "suck", "tuck", "tick", "sick", "sack"],
  ["sock", "suck", "tuck", "tick", "sick", "pick"],
  ["suck", "tuck", "tick", "tack", "sack", "sock"],
  ["suck", "tuck", "tick", "tack", "sack", "sick"],
  ["suck", "tuck", "tick", "tack", "sack", "rack"],
  ["suck", "tuck", "tick", "tack", "sack", "pack"],
  ["suck", "tuck", "tick", "tack", "sack", "back"],
  ["suck", "tuck", "tick", "tack", "rack", "sack"],
  ["tack", "tuck", "tick", "sick", "suck", "sock"],
  ["tack", "tuck", "tick", "sick", "suck", "sack"],
  ["tack", "tuck", "tick", "sick", "suck", "puck"],
  ["tack", "tuck", "tick", "sick", "suck", "luck"],
  ["tack", "tuck", "tick", "sick", "suck", "duck"],
  ["tack", "tuck", "tick", "sick", "suck", "buck"],
  ["thin", "shin", "chin", "chip", "whip", "whiz"],
  ["thin", "shin", "chin", "chip", "chop", "shop"],
  ["thin", "chin", "chip", "chop", "shop", "shot"],
  ["tick", "tuck", "tack", "sack", "suck", "sock"],
  ["tick", "tuck", "tack", "sack", "suck", "sick"],
  ["tick", "tuck", "tack", "sack", "suck", "puck"],
  ["tick", "tuck", "tack", "sack", "suck", "luck"],
  ["tick", "tuck", "tack", "sack", "suck", "duck"],
  ["tick", "tuck", "tack", "sack", "suck", "buck"],
  ["tuck", "tick", "tack", "sack", "suck", "sock"],
  ["tuck", "tick", "tack", "sack", "suck", "sick"],
  ["tuck", "tick", "tack", "sack", "suck", "puck"],
  ["tuck", "tick", "tack", "sack", "suck", "luck"],
  ["tuck", "tick", "tack", "sack", "suck", "duck"],
  ["tuck", "tick", "tack", "sack", "suck", "buck"],
  ["whip", "chip", "chop", "shop", "shot", "shut"],
  ["whiz", "whip", "chip", "chop", "shop", "shot"],
  ["whiz", "whip", "chip", "chin", "thin", "shin"],
  ["whiz", "whip", "chip", "chin", "shin", "thin"],
  ["wish", "fish", "dish", "dash", "rash", "rush"],
  ["wish", "fish", "dish", "dash", "rash", "mash"],
  ["wish", "fish", "dish", "dash", "rash", "lash"],
  ["wish", "fish", "dish", "dash", "rash", "gash"],
  ["wish", "fish", "dish", "dash", "rash", "cash"],
  ["wish", "fish", "dish", "dash", "rash", "bash"],
];


const digraphLadderWords = [
  "ash",
  "back",
  "bash",
  "bath",
  "buck",
  "cash",
  "chat",
  "check",
  "chick",
  "chill",
  "chin",
  "chip",
  "chop",
  "chuck",
  "chug",
  "chum",
  "dash",
  "deck",
  "dish",
  "dock",
  "duck",
  "fish",
  "gash",
  "hill",
  "hush",
  "inch",
  "kick",
  "lash",
  "lick",
  "lock",
  "luck",
  "mash",
  "math",
  "moth",
  "neck",
  "pack",
  "path",
  "peck",
  "pick",
  "puck",
  "quack",
  "quick",
  "rack",
  "rash",
  "rich",
  "rock",
  "rush",
  "sack",
  "shack",
  "shed",
  "shell",
  "shin",
  "shock",
  "shop",
  "shot",
  "shush",
  "shut",
  "sick",
  "sock",
  "suck",
  "tack",
  "thin",
  "tick",
  "tuck",
  "whack",
  "wham",
  "whiff",
  "whip",
  "whiz",
  "wish"
];

const digraphLadderImages = {
  "ash": "images/ash.png",
  "back": "images/back.png",
  "bash": "images/bash.png",
  "bath": "images/bath.png",
  "buck": "images/buck.png",
  "cash": "images/cash.png",
  "chat": "images/chat.png",
  "check": "images/check.png",
  "chick": "images/chick.png",
  "chill": "images/chill.png",
  "chin": "images/chin.png",
  "chip": "images/chip.png",
  "chop": "images/chop.png",
  "chuck": "images/chuck.png",
  "chug": "images/chug.png",
  "chum": "images/chum.png",
  "dash": "images/dash.png",
  "deck": "images/deck.png",
  "dish": "images/dish.png",
  "dock": "images/dock.png",
  "duck": "images/duck.png",
  "fish": "images/fish.png",
  "gash": "images/gash.png",
  "hill": "images/hill.png",
  "hush": "images/hush.png",
  "inch": "images/inch.png",
  "kick": "images/kick.png",
  "lash": "images/lash.png",
  "lick": "images/lick.png",
  "lock": "images/lock.png",
  "luck": "images/luck.png",
  "mash": "images/mash.png",
  "math": "images/math.png",
  "moth": "images/moth.png",
  "neck": "images/neck.png",
  "pack": "images/pack.png",
  "path": "images/path.png",
  "peck": "images/peck.png",
  "pick": "images/pick.png",
  "puck": "images/puck.png",
  "quack": "images/quack.png",
  "quick": "images/quick.png",
  "rack": "images/rack.png",
  "rash": "images/rash.png",
  "rich": "images/rich.png",
  "rock": "images/rock.png",
  "rush": "images/rush.png",
  "sack": "images/sack.png",
  "shack": "images/shack.png",
  "shed": "images/shed.png",
  "shell": "images/shell.png",
  "shin": "images/shin.png",
  "shock": "images/shock.png",
  "shop": "images/shop.png",
  "shot": "images/shot.png",
  "shush": "images/shush.png",
  "shut": "images/shut.png",
  "sick": "images/sick.png",
  "sock": "images/sock.png",
  "suck": "images/suck.png",
  "tack": "images/tack.png",
  "thin": "images/thin.png",
  "tick": "images/tick.png",
  "tuck": "images/tuck.png",
  "whack": "images/whack.png",
  "wham": "images/wham.png",
  "whiff": "images/whiff.png",
  "whip": "images/whip.png",
  "whiz": "images/whiz.png",
  "wish": "images/wish.png",
};
